# DataFrame 

A dataframe = table (rows + columns)

It is most important pandas structure

### 1) Creating Dataframe

In [1]:
import pandas as pd
import numpy as np

# From dictionary
df = pd.DataFrame({
    "Name": ["Aroosa", "Noor", "Qurrat"],
    "Age": [21, 22, 23]
})
df

     Name  Age
0  Aroosa   21
1    Noor   22
2  Qurrat   23

In [29]:
# From list of lists
df2 = pd.DataFrame([
    ["Aroosa", 21],
    ["Noor", 22],
    ["Qurrat", 23]
], columns=["Name", "Age"])
df2

     Name  Age
0  Aroosa   21
1    Noor   22
2  Qurrat   23

In [14]:
# From NumPy array
arr = np.array([[1, 2], [3, 4]])
df3 = pd.DataFrame(arr, columns=["A", "B"])
df3

   A  B
0  1  2
1  3  4

In [16]:

# Empty DataFrame
df4 = pd.DataFrame()
df4

Empty DataFrame
Columns: []
Index: []

### 2) Basic Attributes

In [2]:
print(df.shape)      # (rows, columns)
print(df.size)       # total elements
print(df.ndim)       # dimensions (2)
print(df.columns)    # column names
print(df.index)      # row labels
print(df.dtypes)     # data types
print(df.values)     # numpy array

(3, 2)
6
2
Index(['Name', 'Age'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
Name    object
Age      int64
dtype: object
[['Aroosa' 21]
 ['Noor' 22]
 ['Qurrat' 23]]

In [3]:
df.shape[0] # number of rows by default

3

In [4]:
df

     Name  Age
0  Aroosa   21
1    Noor   22
2  Qurrat   23

In [6]:
print(df.loc[1, 'Age'])

22

### 3) Viewing data

In [3]:
print(df.head())        # first 5 rows
print(df.tail())        # last 5 rows
print(df.sample(2))     # random rows
print(df.info())        # summary
print(df.describe())    # statistics

     Name  Age
0  Aroosa   21
1    Noor   22
2  Qurrat   23
     Name  Age
0  Aroosa   21
1    Noor   22
2  Qurrat   23
     Name  Age
1    Noor   22
0  Aroosa   21
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes
None
        Age
count   3.0
mean   22.0
std     1.0
min    21.0
25%    21.5
50%    22.0
75%    22.5
max    23.0

### 4) Selecting Columns

In [10]:
print(df["Name"])         # single column
df[["Name", "Age"]]            # multiple columns

0    Aroosa
1      Noor
2    Qurrat
Name: Name, dtype: object

     Name  Age
0  Aroosa   21
1    Noor   22
2  Qurrat   23

### 5) Selecting rows (imp)

In [21]:
# By position
print(df.iloc[0]  )      # first row
print(df.iloc[0:2]  )    # first two rows

# By label
print(df.loc[0]  )       # first row
print(df.loc[0:2]  )     # first two rows

# Specific row & column
print(df.iloc[0, 1])
print(df.loc[0, "Age"])

Name    Aroosa
Age         21
Name: 0, dtype: object
     Name  Age
0  Aroosa   21
1    Noor   22
Name    Aroosa
Age         21
Name: 0, dtype: object
     Name  Age
0  Aroosa   21
1    Noor   22
2  Qurrat   23
21
21

### 6) Filtering Data

In [24]:
print(df[df["Age"] > 21])   # filter rows
print()
print(df[df["Name"].str.startswith("A")])  # string filter
print()
print(df[df["Name"].str.endswith("a")])    # string filter
print()
print(df[df["Name"].str.contains("o")])  # string contains
print()
print(df[df["Name"].isin(["Aroosa", "Qurrat"])])  # multiple values
print()
# Multiple conditions
print(df[(df["Age"] > 20) & (df["Age"] < 23)])

     Name  Age
1    Noor   22
2  Qurrat   23

     Name  Age
0  Aroosa   21

     Name  Age
0  Aroosa   21

     Name  Age
0  Aroosa   21
1    Noor   22

     Name  Age
0  Aroosa   21
2  Qurrat   23

     Name  Age
0  Aroosa   21
1    Noor   22

### 7) Adding columns

In [45]:
df["Salary"] = [1000, 2000, 3000]
df

     Name  Age  Salary
0  Aroosa   21    1000
1    Noor   22    2000
2  Qurrat   23    3000

In [46]:
# Derived column
df["Age_plus_5"] = df["Age"] + 5
df

     Name  Age  Salary  Age_plus_5
0  Aroosa   21    1000          26
1    Noor   22    2000          27
2  Qurrat   23    3000          28

### 8) Modifying Data

In [47]:
df.loc[0, "Age"] = 25
df

     Name  Age  Salary  Age_plus_5
0  Aroosa   25    1000          26
1    Noor   22    2000          27
2  Qurrat   23    3000          28

### 9) Deleting Columns/Rows

In [48]:
df.drop("Age_plus_5", axis=1, inplace=True)        # drop column
df

     Name  Age  Salary
0  Aroosa   25    1000
1    Noor   22    2000
2  Qurrat   23    3000

In [49]:
df.drop(0, axis=0)              # drop row

     Name  Age  Salary
1    Noor   22    2000
2  Qurrat   23    3000

### 10) Renaming

In [51]:
df.rename(columns={"Name": "FullName"}, inplace=True)
df

  FullName  Age  Salary
0   Aroosa   25    1000
1     Noor   22    2000
2   Qurrat   23    3000

### 11) Sorting

In [52]:
df.sort_values("Age")

  FullName  Age  Salary
1     Noor   22    2000
2   Qurrat   23    3000
0   Aroosa   25    1000

In [53]:
df.sort_values("Age", ascending=False)

  FullName  Age  Salary
0   Aroosa   25    1000
2   Qurrat   23    3000
1     Noor   22    2000

In [54]:

df.sort_index()

  FullName  Age  Salary
0   Aroosa   25    1000
1     Noor   22    2000
2   Qurrat   23    3000

### 12) Handling Missing Values

In [64]:
import pandas as pd
import numpy as np
df = pd.DataFrame({ #include null values
    "Name": ["Aroosa", "Noor", np.nan, "Qurrat"],
    "Age": [25, np.nan, 30, 35],
    "Salary": [50000, 60000, 70000, np.nan]
})
df

     Name   Age   Salary
0  Aroosa  25.0  50000.0
1    Noor   NaN  60000.0
2     NaN  30.0  70000.0
3  Qurrat  35.0      NaN

In [65]:
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2   True  False   False
3  False  False    True

In [66]:
df.notnull()

    Name    Age  Salary
0   True   True    True
1   True  False    True
2  False   True    True
3   True   True   False

In [67]:
df.dropna()          # remove missing rows

     Name   Age   Salary
0  Aroosa  25.0  50000.0

In [68]:
df.fillna(0)         # replace with value

     Name   Age   Salary
0  Aroosa  25.0  50000.0
1    Noor   0.0  60000.0
2       0  30.0  70000.0
3  Qurrat  35.0      0.0

In [ ]:
df.fillna(df.mean()) # replace with mean but can only concatenate numeric columns

### 13) Aggregation Functions

In [70]:
df["Age"].sum()  # sum of column

np.float64(90.0)

In [ ]:
df["Age"].mean() # mean of column

np.float64(30.0)

In [72]:
df["Age"].max() # maximum value

np.float64(35.0)

In [73]:
df["Age"].min() # minimum value

np.float64(25.0)

In [74]:
df.count() # count non-null values in each column

Name      3
Age       3
Salary    3
dtype: int64

### 14) Apply function

In [ ]:
df["Age"].apply(lambda x: x * 2) # apply function to column

0    50.0
1     NaN
2    60.0
3    70.0
Name: Age, dtype: float64

### 15) Value Counts

In [76]:
df["Name"].value_counts()

Name
Aroosa    1
Noor      1
Qurrat    1
Name: count, dtype: int64

### 16) Unique Values

In [77]:
df["Name"].unique()

array(['Aroosa', 'Noor', nan, 'Qurrat'], dtype=object)

In [78]:
df["Name"].nunique()

3

### 17) Index Operations

In [83]:
df.set_index("Age", inplace=True) # set column as index
df

       Salary
Age
25.0  50000.0
NaN   60000.0
30.0  70000.0
35.0      NaN

In [85]:
df.reset_index(inplace=True)
df

   index   Age   Salary
0      0  25.0  50000.0
1      1   NaN  60000.0
2      2  30.0  70000.0
3      3  35.0      NaN

### 18) Arithmethic Operations

In [86]:
print(df["Age"] + 5)
print(df["Age"] * 2)

0    30.0
1     NaN
2    35.0
3    40.0
Name: Age, dtype: float64
0    50.0
1     NaN
2    60.0
3    70.0
Name: Age, dtype: float64

### 19) Boolean Operations

In [87]:
(df["Age"] > 20) & (df["Age"] < 30)

0     True
1    False
2    False
3    False
Name: Age, dtype: bool

### 20) GroupBy

In [ ]:
df = pd.DataFrame({
    "Dept": ["IT", "IT", "HR", "HR"],
    "Salary": [1000, 2000, 1500, 2500]
})
df

  Dept  Salary
0   IT    1000
1   IT    2000
2   HR    1500
3   HR    2500

In [ ]:
df.groupby("Dept").sum() # group by and sum

      Salary
Dept
HR      4000
IT      3000

In [90]:
 df.groupby("Dept").mean() # group by and calculate mean

      Salary
Dept
HR    2000.0
IT    1500.0

### 21) Merge (like SQL JOIN)

In [98]:
df1 = pd.DataFrame({"ID": [1,2], "Name": ["Aroosa","Kashaf"]})
df1

   ID    Name
0   1  Aroosa
1   2  Kashaf

In [99]:
df2 = pd.DataFrame({"ID": [1,2], "Salary": [1000,2000]})
df2

   ID  Salary
0   1    1000
1   2    2000

In [100]:
pd.merge(df1, df2, on="ID") # merge on common column

   ID    Name  Salary
0   1  Aroosa    1000
1   2  Kashaf    2000

### 22) Concatenate

In [101]:
pd.concat([df1, df2])

   ID    Name  Salary
0   1  Aroosa     NaN
1   2  Kashaf     NaN
0   1     NaN  1000.0
1   2     NaN  2000.0

### 23) Pivot Table
 pivot table is used to summarize data by grouping and applying an aggregation function. In this example, we are calculating the mean salary for each department.

In [102]:
df.pivot_table(values="Salary", index="Dept", aggfunc="mean")

      Salary
Dept
HR    2000.0
IT    1500.0

### 24) Duplicate Handling

In [112]:
df = pd.DataFrame({
    "Name": ["Aroosa","Qurrat", "Noor", "Qurrat"],
    "Age": [21, 23, 21, 23],
    "Salary": [1000, 3000, 2000, 3000]
})
df

     Name  Age  Salary
0  Aroosa   21    1000
1  Qurrat   23    3000
2    Noor   21    2000
3  Qurrat   23    3000

In [113]:
df.duplicated() # check for duplicate rows

0    False
1    False
2    False
3     True
dtype: bool

In [114]:
df.drop_duplicates()

     Name  Age  Salary
0  Aroosa   21    1000
1  Qurrat   23    3000
2    Noor   21    2000

### 25) String Operations

In [115]:
df["Name"].str.upper()

0    AROOSA
1    QURRAT
2      NOOR
3    QURRAT
Name: Name, dtype: object

In [116]:
df["Name"].str.contains("a")

0     True
1     True
2    False
3     True
Name: Name, dtype: bool

### 26) Apply on Entire DataFrame

In [117]:
df.apply(lambda x: x.max())

Name      Qurrat
Age           23
Salary      3000
dtype: object

### 27) Iterating 
not recommended but useful

In [119]:
df

     Name  Age  Salary
0  Aroosa   21    1000
1  Qurrat   23    3000
2    Noor   21    2000
3  Qurrat   23    3000

In [118]:
for index, row in df.iterrows():
    print(row["Name"])

Aroosa
Qurrat
Noor
Qurrat

### 28) Export Data

In [131]:
df = pd.DataFrame({
    "Name": ["Aroosa", "Noor", "Qurrat", "Maheen", "Kashaf", "Sana", "Alina", "Sameen", "Laiba"],
    "Age": [21, 22, 23, 24, 25, 26, 27, 28, 29],
    "Salary": [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]
})

In [122]:
df.to_csv("file.csv", index=False)

In [ ]:
# df.to_excel("file.xlsx")

### 29) Import Data

In [125]:
pd.read_csv("file.csv")

     Name  Age  Salary
0  Aroosa   21    1000
1    Noor   22    2000
2  Qurrat   23    3000
3  Maheen   24    4000
4  Kashaf   25    5000
5    Sana   26    6000
6   Alina   27    7000
7  Sameen   28    8000
8   Laiba   29    9000

In [ ]:
# pd.read_excel("file.xlsx")

### 30) Descriptive stats

In [126]:
df.describe()

             Age       Salary
count   9.000000     9.000000
mean   25.000000  5000.000000
std     2.738613  2738.612788
min    21.000000  1000.000000
25%    23.000000  3000.000000
50%    25.000000  5000.000000
75%    27.000000  7000.000000
max    29.000000  9000.000000

### 31) Correlation

In [ ]:
#df.corr()

### 32) Clipping

In [128]:
df["Age"].clip(18, 25)

0    21
1    22
2    23
3    24
4    25
5    25
6    25
7    25
8    25
Name: Age, dtype: int64

### 34) Ranking

In [129]:
df["Age"].rank() # rank is the position of each value in the sorted order of the column.

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
8    9.0
Name: Age, dtype: float64

### 34) Replace Values

In [132]:
df

     Name  Age  Salary
0  Aroosa   21    1000
1    Noor   22    2000
2  Qurrat   23    3000
3  Maheen   24    4000
4  Kashaf   25    5000
5    Sana   26    6000
6   Alina   27    7000
7  Sameen   28    8000
8   Laiba   29    9000

In [135]:
df.replace(27, 100)

     Name  Age  Salary
0  Aroosa   21    1000
1    Noor   22    2000
2  Qurrat   23    3000
3  Maheen   24    4000
4  Kashaf   25    5000
5    Sana   26    6000
6   Alina  100    7000
7  Sameen   28    8000
8   Laiba   29    9000