# Dataframe
2d arrays

data in the form of tables

In [12]:
# Create a dataframe from a dictionary of list
import pandas as pd
data = {
    'Name': ['Aroosa', 'Noor', 'Qurrat'],
    'Age': [21, 23, 23],
    'City': ['Wah Cantt', 'Islamabad', 'Rawalpindi']
    }

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age        City
0  Aroosa   21   Wah Cantt
1    Noor   23   Islamabad
2  Qurrat   23  Rawalpindi
<class 'pandas.core.frame.DataFrame'>

In [3]:
import numpy as np
np.array(df)

array([['Aroosa', 21, 'Wah Cantt'],
       ['Noor', 23, 'Islamabad'],
       ['Qurrat', 23, 'Rawalpindi']], dtype=object)

In [4]:
# Create a dataframe from list of dictionaries

data = [
    {'Name': 'Aroosa', 'Age': 21, 'City': 'Wah Cantt'},  #one row data
    {'Name': 'Noor', 'Age': 23, 'City': 'Islamabad'},
    {'Name': 'Qurrat', 'Age': 23, 'City': 'Rawalpindi'},
    {'Name': 'Maheen', 'Age' : 19, 'City' : 'Taxila Cantt'}
]

df =  pd.DataFrame(data)
print(df)   
print(type(df))

     Name  Age          City
0  Aroosa   21     Wah Cantt
1    Noor   23     Islamabad
2  Qurrat   23    Rawalpindi
3  Maheen   19  Taxila Cantt
<class 'pandas.core.frame.DataFrame'>

#### Read a csv file

In [7]:
df = pd.read_csv('Online Sales Data.csv')
df.head(5)  # top 5 elements(rows) of the dataframe

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [8]:
df.tail(5)  # bottom 5 elements(rows) of the dataframe

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

#### Accessing data from dataframe

In [11]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [13]:
df

     Name  Age        City
0  Aroosa   21   Wah Cantt
1    Noor   23   Islamabad
2  Qurrat   23  Rawalpindi

In [ ]:
df['Name']  # to access a column of the dataframe use column name

0    Aroosa
1      Noor
2    Qurrat
Name: Name, dtype: object

In [ ]:
type(df['Name']) # picking up one column its series

pandas.core.series.Series

#### loc() --- access row index

In [16]:
df.loc[0]  # to access a row of the dataframe use loc[row index] method

Name       Aroosa
Age            21
City    Wah Cantt
Name: 0, dtype: object

#### iloc() --- index location

In [17]:
df.iloc[0]  # to access a row of the dataframe use iloc[row index] method

Name       Aroosa
Age            21
City    Wah Cantt
Name: 0, dtype: object

In [19]:
df.loc[0][0]

C:\Users\ajabe\AppData\Local\Temp\ipykernel_25696\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Aroosa'

difference between loc and iloc is 

* .loc is label based index

eg df.loc[:, 'A']  --- column named A

* It accepts conditions.
* Includes end index when slicing.

* .iloc is position based index

eg df.iloc[:, 0]  --- first column

* It does not accepts conditions.
* Excluded end index.

Use .loc when you know the labels (names)

Use .iloc when you know the positions (numbers)

In [20]:
df.iloc[0][2]

C:\Users\ajabe\AppData\Local\Temp\ipykernel_25696\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Wah Cantt'

#### Accessing a specified element

In [23]:
df[['Name']]

     Name
0  Aroosa
1    Noor
2  Qurrat

#### Access using at

In [29]:
df.at[1, 'Age']

np.int64(23)

#### Accessing a specified element using iat

In [30]:
df.iat[1, 2]

'Islamabad'

### Data Manipulation with Dataframe

##### Add a new column to the dataframe

In [ ]:

df['Salary'] = [50000, 60000, 70000]
df

     Name  Age        City  Salary
0  Aroosa   21   Wah Cantt   50000
1    Noor   23   Islamabad   60000
2  Qurrat   23  Rawalpindi   70000

##### Remove a column from the dataframe

In [36]:
# Remove a column from the dataframe

#df.drop('Salary') # error since it will check in row first axis = 0 which does not a salary
df.drop('Salary', axis=1) # to remove a column we have to specify axis = 1

     Name  Age        City
0  Aroosa   21   Wah Cantt
1    Noor   23   Islamabad
2  Qurrat   23  Rawalpindi

drop is a temporary operation not a permanent operation it does not save state of dataframe so when running next time it will appear again

In [37]:
df

     Name  Age        City  Salary
0  Aroosa   21   Wah Cantt   50000
1    Noor   23   Islamabad   60000
2  Qurrat   23  Rawalpindi   70000

In order to make it save it we use inplace = True

In [38]:
df.drop('Salary', axis=1, inplace=True) # to remove a column permanently we have to specify inplace = True

In [39]:
df

     Name  Age        City
0  Aroosa   21   Wah Cantt
1    Noor   23   Islamabad
2  Qurrat   23  Rawalpindi

##### Add age to the column

suppose after one year everybody's age increases by one

In [41]:
df ['Age'] =df['Age']+1  # applies to all values of column age
df

     Name  Age        City
0  Aroosa   23   Wah Cantt
1    Noor   25   Islamabad
2  Qurrat   25  Rawalpindi

incremented by one

##### Drop based on row

In [42]:
df.drop(0, inplace=True) # to remove a row permanently we have to specify inplace = True
df

     Name  Age        City
1    Noor   25   Islamabad
2  Qurrat   25  Rawalpindi

In [43]:
df = pd.read_csv('Online Sales Data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [45]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the Dataframe
print("\nDataframe description(Statistical summary):\n", df.describe())

# Group by a column and perform an aggregation
# grouped = df.groupby('Category')['Value'].mean()
# print("Mean value by category:\n", grouped)

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

Dataframe description(Statistical summary):
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [ ]:
df.describe() # statistical analysis of the dataframe

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000