# Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data.

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('Online Sales Data.csv')

# fetch first 5 rows
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [9]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [10]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

all numerical columns

In [11]:
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

object(string)

## Handling missing values

In [12]:
df.isnull()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
235,False,False,False,False,False,False,False,False,False
236,False,False,False,False,False,False,False,False,False
237,False,False,False,False,False,False,False,False,False
238,False,False,False,False,False,False,False,False,False
239,False,False,False,False,False,False,False,False,False

false means no missing values

In [ ]:
df.isnull().any(axis=1) # by default it is axis=0

0      False
1      False
2      False
3      False
4      False
       ...
235    False
236    False
237    False
238    False
239    False
Length: 240, dtype: bool

In [7]:
df.isnull().any()

Transaction ID      False
Date                False
Product Category    False
Product Name        False
Units Sold          False
Unit Price          False
Total Revenue       False
Region              False
Payment Method      False
dtype: bool

In [8]:
df.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

count of missing values

In [4]:
df = pd.read_csv('dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [30]:
df.isnull()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,True,False,False
9996,False,True,False,True,False,False,True,False
9997,False,False,False,False,False,False,True,False
9998,False,False,False,True,False,False,True,False
9999,False,False,False,False,False,False,False,False

In [31]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [32]:
df_filled =df.fillna(0)
df_filled

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,0,UNKNOWN,2023-08-30
9996,TXN_9659401,0,3,0,3.0,Digital Wallet,0,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,0,2023-03-02
9998,TXN_7695629,Cookie,3,0,3.0,Digital Wallet,0,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

filling missing values with 0

In [8]:

# Convert to numeric
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce') # errors='coerce' will convert non-numeric values to NaN

# Fill missing values with mean
df['Price Per Unit_fillNA'] = df['Price Per Unit'].fillna(df['Price Per Unit'].mean())
df


#or in one line
# df['Quantity_fillNA'] = pd.to_numeric(df['Quantity'], errors='coerce').fillna(
#     pd.to_numeric(df['Quantity'], errors='coerce').mean()
# )

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.000000
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.000000
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.000000
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.000000
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.000000
...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30,2.000000
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,2.949984
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,2.000000
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,2.949984
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,4.000000

filling missing values with mean of that column

## Change datatypes

to resolve the conflicts of strings and numbers always check datatype before operations eg,

In [56]:
print(df['Quantity'].dtype)

object

before convert to numeric

In [42]:
print(df['Price Per Unit'].dtype)

object

after converting to numeric

In [54]:
print(df['Price Per Unit'].dtype)

float64

In [9]:
df['Price_Per_Unit_new'] = df['Price Per Unit'].astype(float)
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA,Price_Per_Unit_new
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.0,2.0
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.0,3.0
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.0,1.0
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.0,5.0
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.0,2.0

In [ ]:
df['Price_Per_Unit_new'] = df['Price Per Unit'].astype(int)
df.head()

ValueError: could not convert string to float: 'ERROR'

Error since there are missing values in Price Per Unit column which can be string

In [64]:
df['Price_Per_Unit_new'] = df['Price Per Unit'].fillna(df['Price Per Unit'].mean()).astype(int)
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA,Price_Per_Unit_new
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.0,2
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.0,3
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.0,1
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.0,5
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.0,2

In [45]:
df.dtypes

Transaction ID            object
Item                      object
Quantity                  object
Price Per Unit           float64
Total Spent               object
Payment Method            object
Location                  object
Transaction Date          object
Price Per Unit_fillNA    float64
dtype: object

## Renaming columns

In [47]:
df.rename(columns={'Quantity': 'Number of item'})

,Transaction ID,Item,Number of item,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.000000
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.000000
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.000000
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.000000
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.000000
...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30,2.000000
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,2.949984
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,2.000000
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,2.949984
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,4.000000

In [48]:
df.rename(columns={'Number of item': 'Quantity'})

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.000000
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.000000
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.000000
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.000000
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.000000
...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30,2.000000
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,2.949984
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,2.000000
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,2.949984
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,4.000000

### Apply function to one of the columns using lambda

In [ ]:
df['New Price'] = df['Price Per Unit'].apply(lambda x:x*2)
# use lambda for custom functions
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA,Price_Per_Unit_new,New Price
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.000000,2,4.0
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.000000,3,6.0
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.000000,1,2.0
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.000000,5,10.0
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.000000,2,4.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30,2.000000,2,4.0
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,2.949984,2,NaN
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,2.000000,2,4.0
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,2.949984,2,NaN
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,4.000000,4,8.0

## Implement

In [1]:
import pandas as pd
import numpy as np
data = {
    "name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Eve", None],
    "score": [90, 85, 90, 90, 85, 70, np.nan],
    "year": [2021, 2020, 2021, 2021, 2020, 2019, 2022],
    "city": ["NY", "LA", "NY", "NY", "LA", None, "SF"]
}

df = pd.DataFrame(data)
df

      name  score  year  city
0    Alice   90.0  2021    NY
1      Bob   85.0  2020    LA
2  Charlie   90.0  2021    NY
3    Alice   90.0  2021    NY
4      Bob   85.0  2020    LA
5      Eve   70.0  2019  None
6     None    NaN  2022    SF

In [4]:
print( df["name"].value_counts())
print()
print( df.value_counts())

name
Alice      2
Bob        2
Charlie    1
Eve        1
Name: count, dtype: int64

name     score  year  city
Alice    90.0   2021  NY      2
Bob      85.0   2020  LA      2
Charlie  90.0   2021  NY      1
Name: count, dtype: int64

In [2]:
print( df.sort_values("year"))
print()
print(df.sort_values("year", ascending=False))

      name  score  year  city
5      Eve   70.0  2019  None
1      Bob   85.0  2020    LA
4      Bob   85.0  2020    LA
0    Alice   90.0  2021    NY
3    Alice   90.0  2021    NY
2  Charlie   90.0  2021    NY
6     None    NaN  2022    SF

      name  score  year  city
6     None    NaN  2022    SF
2  Charlie   90.0  2021    NY
0    Alice   90.0  2021    NY
3    Alice   90.0  2021    NY
1      Bob   85.0  2020    LA
4      Bob   85.0  2020    LA
5      Eve   70.0  2019  None

In [3]:
df["score_rank"] = df["score"].rank(ascending=False)
df

      name  score  year  city  score_rank
0    Alice   90.0  2021    NY         2.0
1      Bob   85.0  2020    LA         4.5
2  Charlie   90.0  2021    NY         2.0
3    Alice   90.0  2021    NY         2.0
4      Bob   85.0  2020    LA         4.5
5      Eve   70.0  2019  None         6.0
6     None    NaN  2022    SF         NaN

In [9]:
print(df.isnull())
print()
print(df.dropna())
print()
print(df.dropna(how="all"))
print()
df_filled = df.fillna(0)
print(df_filled)

    name  score   year   city  score_rank
0  False  False  False  False       False
1  False  False  False  False       False
2  False  False  False  False       False
3  False  False  False  False       False
4  False  False  False  False       False
5  False  False  False   True       False
6   True   True  False  False        True

      name  score  year city  score_rank
0    Alice   90.0  2021   NY         2.0
1      Bob   85.0  2020   LA         4.5
2  Charlie   90.0  2021   NY         2.0
3    Alice   90.0  2021   NY         2.0
4      Bob   85.0  2020   LA         4.5

      name  score  year  city  score_rank
0    Alice   90.0  2021    NY         2.0
1      Bob   85.0  2020    LA         4.5
2  Charlie   90.0  2021    NY         2.0
3    Alice   90.0  2021    NY         2.0
4      Bob   85.0  2020    LA         4.5
5      Eve   70.0  2019  None         6.0
6     None    NaN  2022    SF         NaN

      name  score  year city  score_rank
0    Alice   90.0  2021   NY         2.0
1      Bob   85.0  2020   LA         4.5
2  Charlie   90.0  2021   NY         2.0
3    Alice   90.0  2021   NY         2.0
4      Bob   85.0  2020   LA         4.5
5      Eve   70.0  2019    0         6.0
6        0    0.0  2022   SF         0.0

dropna(how="all") means:

* It removes only those rows where all values are missing (NaN)

* If even one value exists, the row stays.

1. Remove rows with any missing values

> df.dropna()

2. Remove rows where specific column is missing

> df.dropna(subset=["name"])

3. Remove columns with all NaN

> df.dropna(axis=1, how="all")

In [10]:
df.fillna({"score": 0, "name": "unknown" , "city" : "unkown"})

      name  score  year    city  score_rank
0    Alice   90.0  2021      NY         2.0
1      Bob   85.0  2020      LA         4.5
2  Charlie   90.0  2021      NY         2.0
3    Alice   90.0  2021      NY         2.0
4      Bob   85.0  2020      LA         4.5
5      Eve   70.0  2019  unkown         6.0
6  unknown    0.0  2022      SF         NaN

## Column manipulation

In [11]:
import pandas as pd
import numpy as np
data = {
    "student_id": [101,102,103,104,105,106,107,108],
    "name": ["Ali","Sara","Ahmed","Zara","Usman","Hina","Bilal","Ayesha"],
    "age": [21,22,20,23,24,21,22,20],
    "city": ["Lahore","Karachi","Islamabad","Lahore","Karachi","Lahore","Islamabad","Karachi"],
    "math_score": [78,88,92,65,70,85,90,60],
    "english_score": [80,75,85,60,72,88,91,65],
    "study_hours": [3,5,6,2,3,4,5,2]
}

df1 = pd.DataFrame(data)
df1

   student_id    name  age       city  math_score  english_score  study_hours
0         101     Ali   21     Lahore          78             80            3
1         102    Sara   22    Karachi          88             75            5
2         103   Ahmed   20  Islamabad          92             85            6
3         104    Zara   23     Lahore          65             60            2
4         105   Usman   24    Karachi          70             72            3
5         106    Hina   21     Lahore          85             88            4
6         107   Bilal   22  Islamabad          90             91            5
7         108  Ayesha   20    Karachi          60             65            2

In [12]:
df1["total_score"] = df1["english_score"] + df1["math_score"]
df1["avg_score"] = df1["total_score"] / 2
df1["is_toper"] = df1["avg_score"] > 90
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper
0,101,Ali,21,Lahore,78,80,3,158,79.0,False
1,102,Sara,22,Karachi,88,75,5,163,81.5,False
2,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False
3,104,Zara,23,Lahore,65,60,2,125,62.5,False
4,105,Usman,24,Karachi,70,72,3,142,71.0,False
5,106,Hina,21,Lahore,85,88,4,173,86.5,False
6,107,Bilal,22,Islamabad,90,91,5,181,90.5,True
7,108,Ayesha,20,Karachi,60,65,2,125,62.5,False

In [13]:
# A col using Category 
# age >= 22 → "Senior"
# age < 22 → "Junior"

# use np.where(condition, if true, if false)
import numpy as np
df1["age_category"] = np.where(df1["age"] >= 22, "Senior",  "Junior")
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,101,Ali,21,Lahore,78,80,3,158,79.0,False,Junior
1,102,Sara,22,Karachi,88,75,5,163,81.5,False,Senior
2,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False,Junior
3,104,Zara,23,Lahore,65,60,2,125,62.5,False,Senior
4,105,Usman,24,Karachi,70,72,3,142,71.0,False,Senior
5,106,Hina,21,Lahore,85,88,4,173,86.5,False,Junior
6,107,Bilal,22,Islamabad,90,91,5,181,90.5,True,Senior
7,108,Ayesha,20,Karachi,60,65,2,125,62.5,False,Junior

In [ ]:
# Droping Col
df1.drop("student_id", axis=1)

,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,Ali,21,Lahore,78,80,3,158,79.0,False,Junior
1,Sara,22,Karachi,88,75,5,163,81.5,False,Senior
2,Ahmed,20,Islamabad,92,85,6,177,88.5,False,Junior
3,Zara,23,Lahore,65,60,2,125,62.5,False,Senior
4,Usman,24,Karachi,70,72,3,142,71.0,False,Senior
5,Hina,21,Lahore,85,88,4,173,86.5,False,Junior
6,Bilal,22,Islamabad,90,91,5,181,90.5,True,Senior
7,Ayesha,20,Karachi,60,65,2,125,62.5,False,Junior

In [16]:
df1.drop("name", axis=1)

,student_id,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,101,21,Lahore,78,80,3,158,79.0,False,Junior
1,102,22,Karachi,88,75,5,163,81.5,False,Senior
2,103,20,Islamabad,92,85,6,177,88.5,False,Junior
3,104,23,Lahore,65,60,2,125,62.5,False,Senior
4,105,24,Karachi,70,72,3,142,71.0,False,Senior
5,106,21,Lahore,85,88,4,173,86.5,False,Junior
6,107,22,Islamabad,90,91,5,181,90.5,True,Senior
7,108,20,Karachi,60,65,2,125,62.5,False,Junior

By default pd functions takes row eg. drop('name') compiler will think of it as row so mentioning     axis = 1 is necessary, if you don't want to mention axis you can write

df1.drop(columns=["student_id"])

df1.drop(columns=["name"])

In [17]:
# Row Filtering
# keep only students with Scores > 70

df1 = df1[df1["math_score"] > 70]
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,101,Ali,21,Lahore,78,80,3,158,79.0,False,Junior
1,102,Sara,22,Karachi,88,75,5,163,81.5,False,Senior
2,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False,Junior
5,106,Hina,21,Lahore,85,88,4,173,86.5,False,Junior
6,107,Bilal,22,Islamabad,90,91,5,181,90.5,True,Senior

👉 1. Inner df1

df1["math_score"] > 70

This is used to create a condition

It checks the "math_score" column of df1

Output is a Boolean mask like:

[True, False, True, ...]

👉 2. Outer df1

df1[ ... ]

This uses that Boolean mask to filter rows

It says:

“From df1, keep only rows where condition is True”

🧠 So the full meaning becomes:

“From df1, keep only those rows of df1 where math_score > 70”

🔍 Think of it like:

Inner df1 → checks

Outer df1 → filters

💥 Simple analogy

Imagine a list of students:

Inner part → “Who scored above 70?” ✅❌

Outer part → “Okay, now only show those students”

In [ ]:
df1[df1["avg_score"] >= 75]
df1 = df1.reset_index(drop=True) # drop=True will drop the old index and create a new one
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,101,Ali,21,Lahore,78,80,3,158,79.0,False,Junior
1,102,Sara,22,Karachi,88,75,5,163,81.5,False,Senior
2,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False,Junior
3,106,Hina,21,Lahore,85,88,4,173,86.5,False,Junior
4,107,Bilal,22,Islamabad,90,91,5,181,90.5,True,Senior

In [19]:
df1 = df1.sort_values("avg_score", ascending=False)
df1 = df1.reset_index(drop=True)
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,107,Bilal,22,Islamabad,90,91,5,181,90.5,True,Senior
1,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False,Junior
2,106,Hina,21,Lahore,85,88,4,173,86.5,False,Junior
3,102,Sara,22,Karachi,88,75,5,163,81.5,False,Senior
4,101,Ali,21,Lahore,78,80,3,158,79.0,False,Junior