# Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data.

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('Online Sales Data.csv')

# fetch first 5 rows
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [9]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [10]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

all numerical columns

In [11]:
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

object(string)

#### Handling missing values

In [12]:
df.isnull()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
235,False,False,False,False,False,False,False,False,False
236,False,False,False,False,False,False,False,False,False
237,False,False,False,False,False,False,False,False,False
238,False,False,False,False,False,False,False,False,False
239,False,False,False,False,False,False,False,False,False

false means no missing values

In [ ]:
df.isnull().any(axis=1) # by default it is axis=0

0      False
1      False
2      False
3      False
4      False
       ...
235    False
236    False
237    False
238    False
239    False
Length: 240, dtype: bool

In [7]:
df.isnull().any()

Transaction ID      False
Date                False
Product Category    False
Product Name        False
Units Sold          False
Unit Price          False
Total Revenue       False
Region              False
Payment Method      False
dtype: bool

In [8]:
df.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

count of missing values

In [4]:
df = pd.read_csv('dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [30]:
df.isnull()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,True,False,False
9996,False,True,False,True,False,False,True,False
9997,False,False,False,False,False,False,True,False
9998,False,False,False,True,False,False,True,False
9999,False,False,False,False,False,False,False,False

In [31]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [32]:
df_filled =df.fillna(0)
df_filled

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,0,UNKNOWN,2023-08-30
9996,TXN_9659401,0,3,0,3.0,Digital Wallet,0,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,0,2023-03-02
9998,TXN_7695629,Cookie,3,0,3.0,Digital Wallet,0,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

filling missing values with 0

In [8]:

# Convert to numeric
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce') # errors='coerce' will convert non-numeric values to NaN

# Fill missing values with mean
df['Price Per Unit_fillNA'] = df['Price Per Unit'].fillna(df['Price Per Unit'].mean())
df


#or in one line
# df['Quantity_fillNA'] = pd.to_numeric(df['Quantity'], errors='coerce').fillna(
#     pd.to_numeric(df['Quantity'], errors='coerce').mean()
# )

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.000000
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.000000
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.000000
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.000000
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.000000
...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30,2.000000
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,2.949984
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,2.000000
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,2.949984
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,4.000000

filling missing values with mean of that column

#### Change datatypes

to resolve the conflicts of strings and numbers always check datatype before operations eg,

In [56]:
print(df['Quantity'].dtype)

object

before convert to numeric

In [42]:
print(df['Price Per Unit'].dtype)

object

after converting to numeric

In [54]:
print(df['Price Per Unit'].dtype)

float64

In [9]:
df['Price_Per_Unit_new'] = df['Price Per Unit'].astype(float)
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA,Price_Per_Unit_new
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.0,2.0
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.0,3.0
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.0,1.0
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.0,5.0
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.0,2.0

In [ ]:
df['Price_Per_Unit_new'] = df['Price Per Unit'].astype(int)
df.head()

ValueError: could not convert string to float: 'ERROR'

Error since there are missing values in Price Per Unit column which can be string

In [64]:
df['Price_Per_Unit_new'] = df['Price Per Unit'].fillna(df['Price Per Unit'].mean()).astype(int)
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA,Price_Per_Unit_new
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.0,2
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.0,3
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.0,1
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.0,5
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.0,2

In [45]:
df.dtypes

Transaction ID            object
Item                      object
Quantity                  object
Price Per Unit           float64
Total Spent               object
Payment Method            object
Location                  object
Transaction Date          object
Price Per Unit_fillNA    float64
dtype: object

#### Renaming columns

In [47]:
df.rename(columns={'Quantity': 'Number of item'})

,Transaction ID,Item,Number of item,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.000000
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.000000
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.000000
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.000000
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.000000
...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30,2.000000
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,2.949984
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,2.000000
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,2.949984
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,4.000000

In [48]:
df.rename(columns={'Number of item': 'Quantity'})

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.000000
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.000000
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.000000
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.000000
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.000000
...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30,2.000000
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,2.949984
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,2.000000
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,2.949984
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,4.000000

#### Apply function to one of the columns using lambda

In [ ]:
df['New Price'] = df['Price Per Unit'].apply(lambda x:x*2)
# use lambda for custom functions
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_fillNA,Price_Per_Unit_new,New Price
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.000000,2,4.0
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.000000,3,6.0
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,1.000000,1,2.0
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,5.000000,5,10.0
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.000000,2,4.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30,2.000000,2,4.0
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,2.949984,2,NaN
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,2.000000,2,4.0
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,2.949984,2,NaN
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,4.000000,4,8.0

### Data Aggregating and Grouping

In [5]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [10]:
grouped_mean= df.groupby('Item')['Price Per Unit'].mean()
print(grouped_mean)

Item
Cake        3.000000
Coffee      2.000000
Cookie      1.000000
ERROR       2.944444
Juice       3.000000
Salad       5.000000
Sandwich    4.000000
Smoothie    4.000000
Tea         1.500000
UNKNOWN     2.880368
Name: Price Per Unit, dtype: float64

“Group the data by Item, then for each item, calculate the average (mean) price per unit.”

In [11]:
grouped_sum = df.groupby(['Item' ,'Location'])['Price Per Unit'].sum()
print(grouped_sum)

Item      Location
Cake      ERROR        141.0
          In-store     918.0
          Takeaway     966.0
          UNKNOWN      150.0
Coffee    ERROR         60.0
          In-store     602.0
          Takeaway     664.0
          UNKNOWN       96.0
Cookie    ERROR         35.0
          In-store     314.0
          Takeaway     341.0
          UNKNOWN       26.0
ERROR     ERROR         37.0
          In-store     239.0
          Takeaway     228.5
          UNKNOWN       28.5
Juice     ERROR         93.0
          In-store    1050.0
          Takeaway     960.0
          UNKNOWN       96.0
Salad     ERROR        180.0
          In-store    1750.0
          Takeaway    1635.0
          UNKNOWN      170.0
Sandwich  ERROR        172.0
          In-store    1416.0
          Takeaway    1308.0
          UNKNOWN      116.0
Smoothie  ERROR        204.0
          In-store    1224.0
          Takeaway    1144.0
          UNKNOWN      120.0
Tea       ERROR         54.0
          In-store     457.5
          Takeaway     480.0
          UNKNOWN       58.5
UNKNOWN   ERROR         30.0
          In-store     267.0
          Takeaway     287.0
          UNKNOWN       23.0
Name: Price Per Unit, dtype: float64

“Group my data by Item AND Location, then for each group, add up (sum) the Price Per Unit.”

	
So instead of treating every row separately, it clusters rows into mini-groups.

After grouping, you say:

👉 “From each group, I only care about this column”


#### 📊 Example 

##### Original Data:

| Item   | Location | Price Per Unit |
| ------ | -------- | -------------- |
| Coffee | In       | 2              |
| Coffee | In       | 3              |
| Coffee | Take     | 2              |
| Cake   | In       | 3              |

---

##### After grouping + sum:

| Item   | Location | Sum |
| ------ | -------- | --- |
| Coffee | In       | 5   |
| Coffee | Take     | 2   |
| Cake   | In       | 3   |

---

In [13]:
grouped_sum = df.groupby(['Item', 'Location'])['Price Per Unit'].sum().reset_index()
print(grouped_sum)

        Item  Location  Price Per Unit
0       Cake     ERROR           141.0
1       Cake  In-store           918.0
2       Cake  Takeaway           966.0
3       Cake   UNKNOWN           150.0
4     Coffee     ERROR            60.0
5     Coffee  In-store           602.0
6     Coffee  Takeaway           664.0
7     Coffee   UNKNOWN            96.0
8     Cookie     ERROR            35.0
9     Cookie  In-store           314.0
10    Cookie  Takeaway           341.0
11    Cookie   UNKNOWN            26.0
12     ERROR     ERROR            37.0
13     ERROR  In-store           239.0
14     ERROR  Takeaway           228.5
15     ERROR   UNKNOWN            28.5
16     Juice     ERROR            93.0
17     Juice  In-store          1050.0
18     Juice  Takeaway           960.0
19     Juice   UNKNOWN            96.0
20     Salad     ERROR           180.0
21     Salad  In-store          1750.0
22     Salad  Takeaway          1635.0
23     Salad   UNKNOWN           170.0
24  Sandwich     ERROR           172.0
25  Sandwich  In-store          1416.0
26  Sandwich  Takeaway          1308.0
27  Sandwich   UNKNOWN           116.0
28  Smoothie     ERROR           204.0
29  Smoothie  In-store          1224.0
30  Smoothie  Takeaway          1144.0
31  Smoothie   UNKNOWN           120.0
32       Tea     ERROR            54.0
33       Tea  In-store           457.5
34       Tea  Takeaway           480.0
35       Tea   UNKNOWN            58.5
36   UNKNOWN     ERROR            30.0
37   UNKNOWN  In-store           267.0
38   UNKNOWN  Takeaway           287.0
39   UNKNOWN   UNKNOWN            23.0

In [14]:
grouped_sum = df.groupby(['Item' ,'Location'])['Price Per Unit'].sum().mean()
print(grouped_sum)

453.525

#### Aggregate multiple functions

In [15]:
grouped_agg = df.groupby('Location')['Price Per Unit'].agg(['mean', 'sum', 'count'])
grouped_agg

              mean     sum  count
Location
ERROR     3.026471  1029.0    340
In-store  2.975393  8524.5   2865
Takeaway  2.909727  8316.0   2858
UNKNOWN   2.853035   893.0    313

👉 “Group data by Location, and for each location, calculate:

* average price
* total price
* number of entries”

.agg means instead of just one operation, you **apply multiple operations** at once:

| Function | Meaning                   |
| -------- | ------------------------- |
| mean     | average                   |
| sum      | total                     |
| count    | number of non-null values |

### Merging and joining Dataframes

In [19]:
df1 = pd.DataFrame({'Key' : ['A', 'B', 'C'], 'Value1' : [1, 2, 3]})
df2 = pd.DataFrame({'Key' : ['A', 'B', 'D'], 'Value2' : [4, 5, 6]})

In [20]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [21]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [ ]:

pd.merge(df1, df2)

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [ ]:
# Merge DataFrame on the 'key columns'
pd.merge(df1, df2, on = "Key", how ="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

👉 “Combine df1 and df2 using the common column ‘Key’, and keep only matching rows.”


* on="Key"

Think of it like:

“Join rows where df1.Key == df2.Key”

* how="inner"
 
👉 This decides what type of merge

INNER JOIN means:

Only keep rows where the key exists in BOTH dataframes

* Other how options

| Type  | Meaning            |
| ----- | ------------------ |
| inner | only matching rows |
| left  | all rows from df1  |
| right | all rows from df2  |
| outer | all rows from both |


Example intuition:

left → “I trust df1, fill from df2 if possible”

outer → “give me EVERYTHING”

In [ ]:
#If column names are different:

pd.merge(df1, df2, left_on="Value1", right_on="Value2")

Empty DataFrame
Columns: [Key_x, Value1, Key_y, Value2]
Index: []

In [28]:
pd.merge(df1, df2, on = "Key", how ="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [29]:
pd.merge(df1, df2, on = "Key", how ="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [30]:
pd.merge(df1, df2, on = "Key", how ="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0