# Handling missing values

None and np.nan (both treated as missing)

In [14]:
import pandas as pd
import numpy as np

data = {
    "name": ["Aroosa", "Ayesha", None, "Noor", None, "Maheen"],
    "age": [20, np.nan, 22, 21, np.nan, 23],
    "marks": [85, 90, np.nan, 88, 76, np.nan],
    "city": ["Islamabad", None, "Lahore", "Karachi", None, "Islamabad"]
}

df = pd.DataFrame(data)
df

     name   age  marks       city
0  Aroosa  20.0   85.0  Islamabad
1  Ayesha   NaN   90.0       None
2    None  22.0    NaN     Lahore
3    Noor  21.0   88.0    Karachi
4    None   NaN   76.0       None
5  Maheen  23.0    NaN  Islamabad

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      float64
 2   marks   4 non-null      float64
 3   city    4 non-null      object
dtypes: float64(2), object(2)
memory usage: 320.0+ bytes

In [5]:
df.isnull()

    name    age  marks   city
0  False  False  False  False
1  False   True  False   True
2   True  False   True  False
3  False  False  False  False
4   True   True  False   True
5  False  False   True  False

In [ ]:
df.isnull().sum() # Count how many missing values are in each column

name     2
age      2
marks    2
city     2
dtype: int64

👉 This tells you:

which columns have missing values

how many in each

In [7]:
df.dropna()

     name   age  marks       city
0  Aroosa  20.0   85.0  Islamabad
3    Noor  21.0   88.0    Karachi

In [8]:
df.dropna(subset=["marks"])

     name   age  marks       city
0  Aroosa  20.0   85.0  Islamabad
1  Ayesha   NaN   90.0       None
3    Noor  21.0   88.0    Karachi
4    None   NaN   76.0       None

dropna(how="all") means:

* It removes only those rows where all values are missing (NaN)

* If even one value exists, the row stays.

1. Remove rows with any missing values

> df.dropna()

2. Remove rows where specific column is missing

> df.dropna(subset=["name"])

3. Remove columns with all NaN

> df.dropna(axis=1, how="all")

In [9]:
df.fillna(0)

     name   age  marks       city
0  Aroosa  20.0   85.0  Islamabad
1  Ayesha   0.0   90.0          0
2       0  22.0    0.0     Lahore
3    Noor  21.0   88.0    Karachi
4       0   0.0   76.0          0
5  Maheen  23.0    0.0  Islamabad

In [13]:
df["age_nonNull"] =df["age"].fillna(df["age"].mean())
df

     name   age  marks       city  age_nonNull
0  Aroosa  20.0   85.0  Islamabad         20.0
1  Ayesha   NaN   90.0       None         21.5
2    None  22.0    NaN     Lahore         22.0
3    Noor  21.0   88.0    Karachi         21.0
4    None   NaN   76.0       None         21.5
5  Maheen  23.0    NaN  Islamabad         23.0

In [15]:
df. drop('age_nonNull',axis=1, inplace=True)

In [20]:
# Forward fill
df.fillna(method="ffill")

C:\Users\ajabe\AppData\Local\Temp\ipykernel_13036\2788844494.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

     name   age  marks       city
0  Aroosa  20.0   85.0  Islamabad
1  Ayesha  20.0   90.0  Islamabad
2  Ayesha  22.0   90.0     Lahore
3    Noor  21.0   88.0    Karachi
4    Noor  21.0   76.0    Karachi
5  Maheen  23.0   76.0  Islamabad

In [21]:
# Backward fill
df.fillna(method="bfill")

C:\Users\ajabe\AppData\Local\Temp\ipykernel_13036\2736007017.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

     name   age  marks       city
0  Aroosa  20.0   85.0  Islamabad
1  Ayesha  22.0   90.0     Lahore
2    Noor  22.0   88.0     Lahore
3    Noor  21.0   88.0    Karachi
4  Maheen  23.0   76.0  Islamabad
5  Maheen  23.0    NaN  Islamabad

In [23]:
# percentage of missig Value in eac col
(df.isnull().sum() / len(df)) * 100

name     33.333333
age      33.333333
marks    33.333333
city     33.333333
dtype: float64

In [ ]:
# Visualize missing Values
df.isnull().sum().sort_values(ascending = False) #descending order

name     2
age      2
marks    2
city     2
dtype: int64

In [31]:
# fill missing Vales
df["filled_age"] = df["age"].fillna(21)
df

     name   age  marks       city  filled_age
0  Aroosa  20.0   85.0  Islamabad        20.0
1  Ayesha   NaN   90.0       None        21.0
2    None  22.0    NaN     Lahore        22.0
3    Noor  21.0   88.0    Karachi        21.0
4    None   NaN   76.0       None        21.0
5  Maheen  23.0    NaN  Islamabad        23.0

In [32]:
df["city"].sample(3) # Randomly sample 3 values from the "city" column

5    Islamabad
1         None
2       Lahore
Name: city, dtype: object

In [ ]:
# Drop columns if >40% missing

threshold = len(df) * 0.5

df = df.dropna(axis = 1, thresh = threshold) # Drop columns with more than 50% missing values

     name   age  marks       city  filled_age
0  Aroosa  20.0   85.0  Islamabad        20.0
1  Ayesha   NaN   90.0       None        21.0
2    None  22.0    NaN     Lahore        22.0
3    Noor  21.0   88.0    Karachi        21.0
4    None   NaN   76.0       None        21.0
5  Maheen  23.0    NaN  Islamabad        23.0

In [41]:
# Fill Missing Perfromance using mean

df["performance_score"] = df["marks"].fillna(df["marks"].mean())
df

     name   age  marks       city  filled_age  performance_score
0  Aroosa  20.0   85.0  Islamabad        20.0              85.00
1  Ayesha   NaN   90.0       None        21.0              90.00
2    None  22.0    NaN     Lahore        22.0              84.75
3    Noor  21.0   88.0    Karachi        21.0              88.00
4    None   NaN   76.0       None        21.0              76.00
5  Maheen  23.0    NaN  Islamabad        23.0              84.75

In [ ]:
df.isna().sum()

name                 2
age                  2
marks                2
city                 2
filled_age           0
performance_score    0
dtype: int64

### Now we'll handle all missing values from the dataframe

In [15]:
df

     name   age  marks       city
0  Aroosa  20.0   85.0  Islamabad
1  Ayesha   NaN   90.0       None
2    None  22.0    NaN     Lahore
3    Noor  21.0   88.0    Karachi
4    None   NaN   76.0       None
5  Maheen  23.0    NaN  Islamabad

In [16]:
df.isnull().sum()

name     2
age      2
marks    2
city     2
dtype: int64

### name column

In [17]:
df["name"] = df["name"].fillna("Unknown")
df

      name   age  marks       city
0   Aroosa  20.0   85.0  Islamabad
1   Ayesha   NaN   90.0       None
2  Unknown  22.0    NaN     Lahore
3     Noor  21.0   88.0    Karachi
4  Unknown   NaN   76.0       None
5   Maheen  23.0    NaN  Islamabad

### age column

In [18]:
df["age"] = df["age"].fillna(df["age"].mean())
df

      name   age  marks       city
0   Aroosa  20.0   85.0  Islamabad
1   Ayesha  21.5   90.0       None
2  Unknown  22.0    NaN     Lahore
3     Noor  21.0   88.0    Karachi
4  Unknown  21.5   76.0       None
5   Maheen  23.0    NaN  Islamabad

### marks column

In [19]:
df["marks"] = df["marks"].fillna(df["marks"].mean())
df

      name   age  marks       city
0   Aroosa  20.0  85.00  Islamabad
1   Ayesha  21.5  90.00       None
2  Unknown  22.0  84.75     Lahore
3     Noor  21.0  88.00    Karachi
4  Unknown  21.5  76.00       None
5   Maheen  23.0  84.75  Islamabad

### city column

#### Option A (most common in exams):

In [11]:
df["city"] = df["city"].fillna("Unknown")
df

      name   age  marks       city
0   Aroosa  20.0  85.00  Islamabad
1   Ayesha  21.5  90.00    Unknown
2  Unknown  22.0  84.75     Lahore
3     Noor  21.0  88.00    Karachi
4  Unknown  21.5  76.00    Unknown
5   Maheen  23.0  84.75  Islamabad

#### Option B (better in real life):

In [20]:
df["city"] = df["city"].fillna(df["city"].mode()[0])
df

      name   age  marks       city
0   Aroosa  20.0  85.00  Islamabad
1   Ayesha  21.5  90.00  Islamabad
2  Unknown  22.0  84.75     Lahore
3     Noor  21.0  88.00    Karachi
4  Unknown  21.5  76.00  Islamabad
5   Maheen  23.0  84.75  Islamabad

mode() = most frequent value

### Verify

In [21]:
df.isnull().sum()

name     0
age      0
marks    0
city     0
dtype: int64

### Clean table

In [22]:
df

      name   age  marks       city
0   Aroosa  20.0  85.00  Islamabad
1   Ayesha  21.5  90.00  Islamabad
2  Unknown  22.0  84.75     Lahore
3     Noor  21.0  88.00    Karachi
4  Unknown  21.5  76.00  Islamabad
5   Maheen  23.0  84.75  Islamabad

Hence the data is cleaned now.

In [23]:
# In one go
# df["name"] = df["name"].fillna("Unknown")
# df["age"] = df["age"].fillna(df["age"].mean())
# df["marks"] = df["marks"].fillna(df["marks"].mean())
# df["city"] = df["city"].fillna(df["city"].mode()[0])