# Group-by

groupby() in pandas is one of the most important concepts for data analysis. It’s used to split data into groups, apply operations, and combine results.

👉 groupby() means:

> “Group similar data together, then perform calculations on each group separately.”

### Categorical VS Numerical data

Categorical data = data that represents labels / groups / categories (not numbers you calculate with).

It answers:

“Which type / group does this belong to?”

eg, gender, age, city, grade, section, subscription, payment method

and Numerical says "How much?"

1. Nominal (NO ORDER)

👉 Just labels

* gender
* city
* country

❌ No ranking

2. Ordinal (HAS ORDER)

👉 Order matters

* grades: A > B > C
* ratings: 1 ⭐ to 5 ⭐
* education: school → college → university

👉 Still NOT numeric, but ordered


| Column Type | How to fill      |
| ----------- | ---------------- |
| Numeric     | mean / median    |
| Categorical | mode / "Unknown" |

#### DataFrame

In [10]:
import pandas as pd

data = {
    "name": ["Ali", "Sara", "Noor", "Zain", "Hina"],
    "city": ["Lahore", "Lahore", "Karachi", "Karachi", "Lahore"],
    "marks": [80, 90, 85, 70, 95],
    "age": [20, 21, 22, 23, 21]
}

df = pd.DataFrame(data)
df

   name     city  marks  age
0   Ali   Lahore     80   20
1  Sara   Lahore     90   21
2  Noor  Karachi     85   22
3  Zain  Karachi     70   23
4  Hina   Lahore     95   21

#### Group-by one column

* Average marks per city

In [5]:
df.groupby("city")["marks"].mean()

city
Karachi    77.500000
Lahore     88.333333
Name: marks, dtype: float64

#### Group by multiple columns

In [7]:
df.groupby(["city", "age"])["marks"].mean()

city     age
Karachi  22     85.0
         23     70.0
Lahore   20     80.0
         21     92.5
Name: marks, dtype: float64

 
### Multiple Aggregate Functions

* Using Dict:

> df.groupby().agg({"col name": "func" , "col name2": "func"})

specific Fnction on specfic col

* using list:

> df.groupby().agg( ["func", "func2] )

apply these function on ever col

* merge

> df.groupby.agg( {"col name": ["func1" , "func2" ]} )

In [6]:
df.groupby("city")["marks"].agg(["mean", "sum", "count"])

              mean  sum  count
city
Karachi  77.500000  155      2
Lahore   88.333333  265      3

#### Grouping multiple columns

In [8]:
df.groupby("city")[["marks", "age"]].mean()

             marks        age
city
Karachi  77.500000  22.500000
Lahore   88.333333  20.666667

#### Size of each group
tells how many rows in each group

In [12]:
df.groupby("city").size()

city
Karachi    2
Lahore     3
dtype: int64

#### Get group as DataFrame

In [14]:
df.groupby("city").get_group("Lahore")
#returns only Lahore data

   name    city  marks  age
0   Ali  Lahore     80   20
1  Sara  Lahore     90   21
4  Hina  Lahore     95   21

#### Iterating groups

In [ ]:
for name, group in df.groupby("city"):
    print(name)
    print(group)
# prints each group separately

Karachi
   name     city  marks  age
2  Noor  Karachi     85   22
3  Zain  Karachi     70   23
Lahore
   name    city  marks  age
0   Ali  Lahore     80   20
1  Sara  Lahore     90   21
4  Hina  Lahore     95   21

### Using custom aggregation

In [16]:
df.groupby("city").agg({
    "marks": "mean",
    "age": "max"
})

             marks  age
city
Karachi  77.500000   23
Lahore   88.333333   21

> Key concept: Split → Apply → Combine

groupby() works in 3 steps:

1. Split

Divide data into groups

2. Apply

Perform function (mean, sum, etc.)

3. Combine

Return final result

In [15]:
import pandas as pd
df = pd.read_csv("dirty_cafe_sales.csv")
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [16]:
print(df['Price Per Unit'].dtype)

object

In [18]:
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')

In [19]:
print(df['Price Per Unit'].dtype)

float64

In [20]:
grouped_mean= df.groupby('Item')['Price Per Unit'].mean()
print(grouped_mean)

Item
Cake        3.000000
Coffee      2.000000
Cookie      1.000000
ERROR       2.944444
Juice       3.000000
Salad       5.000000
Sandwich    4.000000
Smoothie    4.000000
Tea         1.500000
UNKNOWN     2.880368
Name: Price Per Unit, dtype: float64

Group the data by Item, then for each item, calculate the average (mean) price per unit.

In [21]:
grouped_sum = df.groupby(['Item' ,'Location'])['Price Per Unit'].sum()
print(grouped_sum)

Item      Location
Cake      ERROR        141.0
          In-store     918.0
          Takeaway     966.0
          UNKNOWN      150.0
Coffee    ERROR         60.0
          In-store     602.0
          Takeaway     664.0
          UNKNOWN       96.0
Cookie    ERROR         35.0
          In-store     314.0
          Takeaway     341.0
          UNKNOWN       26.0
ERROR     ERROR         37.0
          In-store     239.0
          Takeaway     228.5
          UNKNOWN       28.5
Juice     ERROR         93.0
          In-store    1050.0
          Takeaway     960.0
          UNKNOWN       96.0
Salad     ERROR        180.0
          In-store    1750.0
          Takeaway    1635.0
          UNKNOWN      170.0
Sandwich  ERROR        172.0
          In-store    1416.0
          Takeaway    1308.0
          UNKNOWN      116.0
Smoothie  ERROR        204.0
          In-store    1224.0
          Takeaway    1144.0
          UNKNOWN      120.0
Tea       ERROR         54.0
          In-store     457.5
          Takeaway     480.0
          UNKNOWN       58.5
UNKNOWN   ERROR         30.0
          In-store     267.0
          Takeaway     287.0
          UNKNOWN       23.0
Name: Price Per Unit, dtype: float64

“Group my data by Item AND Location, then for each group, add up (sum) the Price Per Unit.”

	
So instead of treating every row separately, it clusters rows into mini-groups.

After grouping, you say:

👉 “From each group, I only care about this column”


#### 📊 Example 

##### Original Data:

| Item   | Location | Price Per Unit |
| ------ | -------- | -------------- |
| Coffee | In       | 2              |
| Coffee | In       | 3              |
| Coffee | Take     | 2              |
| Cake   | In       | 3              |

---

##### After grouping + sum:

| Item   | Location | Sum |
| ------ | -------- | --- |
| Coffee | In       | 5   |
| Coffee | Take     | 2   |
| Cake   | In       | 3   |

---

In [22]:
grouped_sum = df.groupby(['Item', 'Location'])['Price Per Unit'].sum().reset_index()
print(grouped_sum)

        Item  Location  Price Per Unit
0       Cake     ERROR           141.0
1       Cake  In-store           918.0
2       Cake  Takeaway           966.0
3       Cake   UNKNOWN           150.0
4     Coffee     ERROR            60.0
5     Coffee  In-store           602.0
6     Coffee  Takeaway           664.0
7     Coffee   UNKNOWN            96.0
8     Cookie     ERROR            35.0
9     Cookie  In-store           314.0
10    Cookie  Takeaway           341.0
11    Cookie   UNKNOWN            26.0
12     ERROR     ERROR            37.0
13     ERROR  In-store           239.0
14     ERROR  Takeaway           228.5
15     ERROR   UNKNOWN            28.5
16     Juice     ERROR            93.0
17     Juice  In-store          1050.0
18     Juice  Takeaway           960.0
19     Juice   UNKNOWN            96.0
20     Salad     ERROR           180.0
21     Salad  In-store          1750.0
22     Salad  Takeaway          1635.0
23     Salad   UNKNOWN           170.0
24  Sandwich     ERROR           172.0
25  Sandwich  In-store          1416.0
26  Sandwich  Takeaway          1308.0
27  Sandwich   UNKNOWN           116.0
28  Smoothie     ERROR           204.0
29  Smoothie  In-store          1224.0
30  Smoothie  Takeaway          1144.0
31  Smoothie   UNKNOWN           120.0
32       Tea     ERROR            54.0
33       Tea  In-store           457.5
34       Tea  Takeaway           480.0
35       Tea   UNKNOWN            58.5
36   UNKNOWN     ERROR            30.0
37   UNKNOWN  In-store           267.0
38   UNKNOWN  Takeaway           287.0
39   UNKNOWN   UNKNOWN            23.0

In [23]:
grouped_agg = df.groupby('Location')['Price Per Unit'].agg(['mean', 'sum', 'count'])
grouped_agg

              mean     sum  count
Location
ERROR     3.026471  1029.0    340
In-store  2.975393  8524.5   2865
Takeaway  2.909727  8316.0   2858
UNKNOWN   2.853035   893.0    313

👉 “Group data by Location, and for each location, calculate:

* average price
* total price
* number of entries”

.agg means instead of just one operation, you **apply multiple operations** at once:

| Function | Meaning                   |
| -------- | ------------------------- |
| mean     | average                   |
| sum      | total                     |
| count    | number of non-null values |

In [25]:
movies = pd.read_csv("imdb-top-1000.csv")
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [26]:
genre = movies.groupby("Genre")

In [27]:
# now Genre Has split Whole Dataset in group bsed on Genres
genre.sum().head(3)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0

In [28]:
genre.max().head(3)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0

In [29]:
# Find top 3 genre by total earnings  
# now we Only need Gross Col we dont need to calculate for other cols in a group 
# so we Specify it
movies.groupby("Genre")["Gross"].sum().sort_values(ascending = False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [30]:
# find the Genre which has highiest avg imdb rating

movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending = False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [32]:
#find Directory who is most poular  ( nmbr of votes )

movies.groupby("Director")["No_of_Votes"].sum().sort_values(ascending = False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [33]:
# find number of movies done by each Actor

movies["Star1"].value_counts()

Star1
Tom Hanks            12
Robert De Niro       11
Al Pacino            10
Clint Eastwood       10
Humphrey Bogart       9
                     ..
Phil Harris           1
David Hemmings        1
John Lennon           1
Tallulah Bankhead     1
Bruce Lee             1
Name: count, Length: 660, dtype: int64

In [34]:
# find total number of groups

print(movies.groupby("Genre").ngroups)

14

In [36]:
len(df.groupby("Genre"))

14

In [ ]:
# find no. of rows in each group

df.groupby("Genre").size() # same as value_counts() but for groupby object

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [ ]:
# find first, last, nth value of each group

df.groupby("Genre").first() # gives first value of each group (first row of each group)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [ ]:
df.groupby("Genre").last() # same as first but it gives last value of each group (last row of each group)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [ ]:
df.groupby("Genre").nth(0) #  gives nth value of each group (nth row of each group) 
# if we give -1 it gives last row of each group same as last() method

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [50]:
df.groupby("Genre").get_group("Action")

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
968,Falling Down,1993,113,Action,7.6,Joel Schumacher,Michael Douglas,171640,40903593.0,56.0
979,Lethal Weapon,1987,109,Action,7.6,Richard Donner,Mel Gibson,236894,65207127.0,68.0
982,Mad Max 2,1981,96,Action,7.6,George Miller,Mel Gibson,166588,12465371.0,77.0
983,The Warriors,1979,92,Action,7.6,Walter Hill,Michael Beck,93878,22490039.0,65.0
985,Escape from Alcatraz,1979,112,Action,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0

### Multiple Aggregate Functions

* Using Dict:

> df.groupby().agg({"col name": "func" , "col name2": "func"})

specific Fnction on specfic col

* using list:

> df.groupby().agg( ["func", "func2] )

apply these function on ever col

* merge

> df.groupby.agg( {"col name": ["func1" , "func2" ]} )

In [51]:
genre.sum().head(1)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0

In [52]:
# apply specific function on specifc col

genre.agg( 
    {
        "Runtime": "mean",
        "IMDB_Rating": "mean",
        "No_of_Votes": "sum",
        "Gross": "sum",
        "Metascore": "min"
    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [53]:
genre.agg( ["max", "min"])
# now each col has min max col

                                  Series_Title  \
                                           max
Genre
Action                                 Yôjinbô
Adventure                           Zombieland
Animation          Ôkami kodomo no Ame to Yuki
Biography                              Zerkalo
Comedy                Zindagi Na Milegi Dobara
Crime                        À bout de souffle
Drama                                Zwartboek
Family     Willy Wonka & the Chocolate Factory
Fantasy                              Nosferatu
Film-Noir                        The Third Man
Horror                               The Thing
Mystery                                Vertigo
Thriller                       Wait Until Dark
Western                 The Outlaw Josey Wales

                                           Released_Year       Runtime       \
                                       min           max   min     max  min
Genre
Action                                 300          2019  1924     321   45
Adventure            2001: A Space Odyssey            PG  1925     228   88
Animation                            Akira          2020  1940     137   71
Biography                 12 Years a Slave          2020  1928     209   93
Comedy                (500) Days of Summer          2020  1921     188   68
Crime                         12 Angry Men          2019  1931     229   80
Drama                                 1917          2020  1925     242   64
Family          E.T. the Extra-Terrestrial          1982  1971     115  100
Fantasy       Das Cabinet des Dr. Caligari          1922  1920      94   76
Film-Noir                Shadow of a Doubt          1949  1941     108  100
Horror                               Alien          2017  1933     122   71
Mystery                          Dark City          2012  1938     138   96
Thriller                   Wait Until Dark          1967  1967     108  108
Western    Il buono, il brutto, il cattivo          1976  1965     165  132

          IMDB_Rating               Director                         \
                  max  min               max                    min
Genre
Action            9.0  7.6       Zack Snyder       Abhishek Chaubey
Adventure         8.6  7.6  Ömer Faruk Sorak         Akira Kurosawa
Animation         8.6  7.6   Yoshifumi Kondô            Adam Elliot
Biography         8.9  7.6      Tom McCarthy             Adam McKay
Comedy            8.6  7.6       Zoya Akhtar  Alejandro G. Iñárritu
Crime             9.2  7.6      Yavuz Turgul         Akira Kurosawa
Drama             9.3  7.6       Çagan Irmak             Aamir Khan
Family            7.8  7.8  Steven Spielberg             Mel Stuart
Fantasy           8.1  7.9      Robert Wiene            F.W. Murnau
Film-Noir         8.1  7.8       John Huston       Alfred Hitchcock
Horror            8.5  7.6  William Friedkin     Alejandro Amenábar
Mystery           8.4  7.6     Terry Gilliam            Alex Proyas
Thriller          7.8  7.8     Terence Young          Terence Young
Western           8.8  7.8      Sergio Leone         Clint Eastwood

                      Star1                           No_of_Votes          \
                        max                       min         max     min
Genre
Action         Yun-Fat Chow                Aamir Khan     2303232   25312
Adventure      Yves Montand                Aamir Khan     1512360   29999
Animation      Yôji Matsuda             Adrian Molina      999790   25229
Biography     Éric Toledano              Adrien Brody     1213505   27254
Comedy     Ömer Faruk Sorak                Aamir Khan      939631   26337
Crime        Vincent Cassel                Ajay Devgn     1826188   27712
Drama        Çetin Tekindor                Abhay Deol     2343110   25088
Family         Henry Thomas               Gene Wilder      372490  178731
Fantasy       Werner Krauss               Max Schreck       88794   57428
Film-Noir     Teresa Wright           Humphrey Bogart      158731   59556
Horror     Sigourney Weaver           Anthony Perkins      787806   27007
Mystery         Vidya Balan  Bernard-Pierre Donnadieu     1129894   33982
Thriller     Audrey Hepburn            Audrey Hepburn       27733   27733
Western         Henry Fonda            Clint Eastwood      688390   65659

                 Gross              Metascore
                   max          min       max   min
Genre
Action     936662225.0       3296.0      98.0  33.0
Adventure  874211619.0      61001.0     100.0  41.0
Animation  873839108.0     128985.0      96.0  61.0
Biography  753585104.0      21877.0      97.0  48.0
Comedy     886752933.0       1305.0      99.0  45.0
Crime      790482117.0       6013.0     100.0  47.0
Drama      924558264.0       3600.0     100.0  28.0
Family     435110554.0    4000000.0      91.0  67.0
Fantasy    445151978.0  337574718.0       NaN   NaN
Film-Noir  123353292.0     449191.0      97.0  94.0
Horror     298791505.0      89029.0      97.0  46.0
Mystery    474203697.0    1035953.0     100.0  52.0
Thriller    17550741.0   17550741.0      81.0  81.0
Western     31800000.0    5321508.0      90.0  69.0

In [54]:
genre.agg( 
    {
        "Runtime": ["min", "max"],
        "IMDB_Rating": ["min", "max"],
        "No_of_Votes": ["sum", "mean"],
        "Gross" :    ["sum", "max", "min"]
    }
)

          Runtime      IMDB_Rating      No_of_Votes                 \
              min  max         min  max         sum           mean
Genre
Action         45  321         7.6  9.0    72282412  420246.581395
Adventure      88  228         7.6  8.6    22576163  313557.819444
Animation      71  137         7.6  8.6    21978630  268032.073171
Biography      93  209         7.6  8.9    24006844  272805.045455
Comedy         68  188         7.6  8.6    27620327  178195.658065
Crime          80  229         7.6  9.2    33533615  313398.271028
Drama          64  242         7.6  9.3    61367304  212343.612457
Family        100  115         7.8  7.8      551221  275610.500000
Fantasy        76   94         7.9  8.1      146222   73111.000000
Film-Noir     100  108         7.8  8.1      367215  122405.000000
Horror         71  122         7.6  8.5     3742556  340232.363636
Mystery        96  138         7.6  8.4     4203004  350250.333333
Thriller      108  108         7.8  7.8       27733   27733.000000
Western       132  165         7.8  8.8     1289665  322416.250000

                  Gross
                    sum          max          min
Genre
Action     3.263226e+10  936662225.0       3296.0
Adventure  9.496922e+09  874211619.0      61001.0
Animation  1.463147e+10  873839108.0     128985.0
Biography  8.276358e+09  753585104.0      21877.0
Comedy     1.566387e+10  886752933.0       1305.0
Crime      8.452632e+09  790482117.0       6013.0
Drama      3.540997e+10  924558264.0       3600.0
Family     4.391106e+08  435110554.0    4000000.0
Fantasy    7.827267e+08  445151978.0  337574718.0
Film-Noir  1.259105e+08  123353292.0     449191.0
Horror     1.034649e+09  298791505.0      89029.0
Mystery    1.256417e+09  474203697.0    1035953.0
Thriller   1.755074e+07   17550741.0   17550741.0
Western    5.822151e+07   31800000.0    5321508.0

In [58]:
# find Nmbr of movies starting with A for each group 

def starts_A(group):
    return group["Series_Title"].str.startswith('A').sum()

genre.apply(starts_A)

C:\Users\ajabe\AppData\Local\Temp\ipykernel_20616\2736517282.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(starts_A)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [59]:
def normal(group):
    group["norm_rating"] = group["IMDB_Rating"].min() / (group["IMDB_Rating"].max() - group["IMDB_Rating"].min())
    return group

genre.apply(normal)

C:\Users\ajabe\AppData\Local\Temp\ipykernel_20616\3635021881.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  group["norm_rating"] = group["IMDB_Rating"].min() / (group["IMDB_Rating"].max() - group["IMDB_Rating"].min())
C:\Users\ajabe\AppData\Local\Temp\ipykernel_20616\3635021881.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  group["norm_rating"] = group["IMDB_Rating"].min() / (group["IMDB_Rating"].max() - group["IMDB_Rating"].min())
C:\Users\ajabe\AppData\Local\Temp\ipykernel_20616\3635021881.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              norm_rating
Genre
Action   2       5.428571
         5       5.428571
         8       5.428571
         10      5.428571
         13      5.428571
...                   ...
Thriller 700          inf
Western  12      7.800000
         48      7.800000
         115     7.800000
         691     7.800000

[1000 rows x 11 columns]

In [ ]:
# which actor genre combo is best in meta score

movies.groupby(["Genre", "Star1"])["Metascore"].mean()

Genre     Star1
Action    Aamir Khan                    NaN
          Aaron Taylor-Johnson    66.000000
          Akshay Kumar                  NaN
          Alan Mak                75.000000
          Alia Bhatt                    NaN
                                    ...
Mystery   Rufus Sewell            66.000000
          Vidya Balan                   NaN
Thriller  Audrey Hepburn          81.000000
Western   Clint Eastwood          77.666667
          Henry Fonda             80.000000
Name: Metascore, Length: 829, dtype: float64