# Concatenation, Join & Merge


| Method     | Think of it as                             |
| ---------- | ------------------------------------------ |
| `concat()` | stacking data (top/bottom or side-by-side) |
| `merge()`  | SQL-style join using keys                  |
| `join()`   | shortcut for merge (index-based)           |

### **1. concat() → “Stack or glue DataFrames”**

-> Use when:
* DataFrames have same columns
* You want to append rows or combine columns

In [ ]:
import pandas as pd

# row-wise concatenation
df1 = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df2 = pd.DataFrame({"A": [5, 6], "B": [7, 8]})

pd.concat([df1, df2])

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [3]:
# column-wise concatenation
pd.concat([df1, df2], axis=1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [4]:
pd.concat([df1, df2], ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [6]:
pd.concat([df1, df2], keys = ["First", "Second"])

          A  B
First  0  1  3
       1  2  4
Second 0  5  7
       1  6  8

concat = just stick DataFrames together (no matching logic)

### **2. merge() → “Database-style join”**

-> Use when:
* You have common column (key)
* Like SQL JOIN

In [ ]:
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Aroosa", "Noor", "Qurrat"]
})

df2 = pd.DataFrame({
    "id": [0, 2, 3],
    "marks": [80, 90, 70]
})

   id    name  marks
0   2    Noor     90
1   3  Qurrat     70

In [12]:
df1

   id    name
0   1  Aroosa
1   2    Noor
2   3  Qurrat

In [13]:
df2

   id  marks
0   0     80
1   2     90
2   3     70

In [14]:
pd.merge(df1, df2, on="id")

   id    name  marks
0   2    Noor     90
1   3  Qurrat     70

👉 “Combine df1 and df2 using the common column 'id', and keep only matching rows.”


* on="id"

Think of it like:

“Join rows where df1.id == df2.id”

#### **Types of join**

| Type  | Meaning            |
| ----- | ------------------ |
| inner | only matching rows |
| left  | all rows from df1  |
| right | all rows from df2  |
| outer | all rows from both |

##### 1. Inner (default) ---intersection

In [11]:
pd.merge(df1, df2, on="id", how="inner")

   id    name  marks
0   2    Noor     90
1   3  Qurrat     70

* how="inner"
 
👉 This decides what type of merge

INNER JOIN means:

Only keep rows where the key exists in BOTH dataframes

##### 2. Left join

In [15]:
pd.merge(df1, df2, on="id", how="left")

   id    name  marks
0   1  Aroosa    NaN
1   2    Noor   90.0
2   3  Qurrat   70.0

Analogy: left → “I trust df1, fill from df2 if possible”

##### 3. Right join

In [16]:
pd.merge(df1, df2, on="id", how="right")

   id    name  marks
0   0     NaN     80
1   2    Noor     90
2   3  Qurrat     70

Analogy: right → “I trust df2, fill from df1 if possible”

##### 4. Outer join --- union

In [17]:
pd.merge(df1, df2, on="id", how="outer")

   id    name  marks
0   0     NaN   80.0
1   1  Aroosa    NaN
2   2    Noor   90.0
3   3  Qurrat   70.0

Analogy: outer → “give me EVERYTHING”

### **3. join() → “Index-based merge (shortcut)”**

-> Use when:
* joining on index
* simpler syntax

In [18]:
df1 = pd.DataFrame({"A": [1, 2]}, index=["a", "b"])
df2 = pd.DataFrame({"B": [3, 4]}, index=["a", "b"])

df1.join(df2)

   A  B
a  1  3
b  2  4

In [20]:
df1.join(df2, how="inner")

   A  B
a  1  3
b  2  4

👉 If you need matching → use merge

👉 If you just want to stack → use concat

### Implementation

In [24]:
Jan= pd.read_csv("reg-month1.csv")
Feb = pd.read_csv("reg-month2.csv")

In [25]:
pd.concat([Jan, Feb] , ignore_index=True)

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [28]:
pd.concat([Jan, Feb], keys=["January", "February"])

             student_id  course_id
January  0           23          1
         1           15          5
         2           18          6
         3           23          4
         4           16          9
         5           18          1
         6            1          1
         7            7          8
         8           22          3
         9           15          1
         10          19          4
         11           1          6
         12           7         10
         13          11          7
         14          13          3
         15          24          4
         16          21          1
         17          16          5
         18          23          3
         19          17          7
         20          23          6
         21          25          1
         22          19          2
         23          25         10
         24           3          3
February 0            3          5
         1           16          7
         2           12         10
         3           12          1
         4           14          9
         5            7          7
         6            7          2
         7           16          3
         8           17         10
         9           11          8
         10          14          6
         11          12          5
         12          12          7
         13          18          8
         14           1         10
         15           1          9
         16           2          5
         17           7          6
         18          22          5
         19          22          6
         20          23          9
         21          23          5
         22          14          4
         23          14          1
         24          11         10
         25          42          9
         26          50          8
         27          38          1

In [30]:
both = pd.concat([Jan, Feb], keys=["January", "February"])

print ( both.loc["January"].head(2) ) # gives January data top 2
print ( both.loc["February"].tail(4) ) # print 0 index in February

   student_id  course_id
0          23          1
1          15          5
    student_id  course_id
24          11         10
25          42          9
26          50          8
27          38          1

In [31]:
import pandas as pd

students = pd.DataFrame({
"id":[1,2,3,4],
"name":["Aroosa", "Alina", "Sana", "Alyan"]
})

scores = pd.DataFrame({
"id":[1,2,2,5],
"score":[85,90,88,70]
})

In [32]:
students

   id    name
0   1  Aroosa
1   2   Alina
2   3    Sana
3   4   Alyan

In [33]:
scores

   id  score
0   1     85
1   2     90
2   2     88
3   5     70

In [35]:
pd.merge(students, scores, on="id", how="inner")

   id    name  score
0   1  Aroosa     85
1   2   Alina     90
2   2   Alina     88

In [36]:
pd.merge(students, scores, on="id", how="outer")

   id    name  score
0   1  Aroosa   85.0
1   2   Alina   90.0
2   2   Alina   88.0
3   3    Sana    NaN
4   4   Alyan    NaN
5   5     NaN   70.0

In [37]:
pd.merge(students, scores, on="id", how="left")

   id    name  score
0   1  Aroosa   85.0
1   2   Alina   90.0
2   2   Alina   88.0
3   3    Sana    NaN
4   4   Alyan    NaN

In [38]:
pd.merge(students, scores, on="id", how="right")

   id    name  score
0   1  Aroosa     85
1   2   Alina     90
2   2   Alina     88
3   5     NaN     70