In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('dogs_dirty_dataset.csv')
df

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,vaccinated,neutered,owner_city,...,sensor_metric_21,sensor_metric_22,sensor_metric_23,sensor_metric_24,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30
0,1599,Luna,Beagle,16.0,36.74,10.51,Black,No,Yes,Karachi,...,error,missing,error,NaN,46.26,missing,NaN,NaN,error,error
1,1902,Cooper,Golden Retriever,6.0,6.35,44.84,NaN,NaN,NaN,NaN,...,7.06,49.83,missing,NaN,46.26,error,missing,error,missing,NaN
2,6904,NaN,Beagle,21.0,NaN,17.16,Black,Yes,NaN,Sydney,...,NaN,NaN,NaN,33.4,missing,60.19,NaN,missing,missing,error
3,5197,Milo,Labrador,-1.0,NaN,unknown,White,No,Yes,Berlin,...,NaN,49.83,82.12,error,error,missing,NaN,error,15.35,70.55
4,6704,Bailey,NaN,21.0,unknown,41.41,White,Yes,No,Berlin,...,missing,NaN,NaN,error,error,60.19,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40595,7203,Bear,Mixed,-2.0,NaN,unknown,NaN,NaN,Yes,London,...,7.06,49.83,missing,missing,error,NaN,error,NaN,missing,missing
40596,6696,Bear,Unknown,20.0,40.99,33.79,Mixed,No,Yes,Karachi,...,missing,missing,NaN,missing,missing,NaN,40.42,NaN,NaN,NaN
40597,7365,Milo,Pug,3.0,16.98,13.75kg,White,NaN,Yes,Karachi,...,7.06,NaN,missing,NaN,error,error,missing,NaN,15.35,70.55
40598,2444,NaN,NaN,0.0,18.35,23.22,Mixed,Yes,NaN,Berlin,...,NaN,error,error,NaN,46.26,error,NaN,error,missing,missing
40599,6868,Duke,Poodle,12.0,40.34kg,31.66,Brown,No,NaN,London,...,missing,49.83,NaN,NaN,NaN,missing,NaN,missing,missing,70.55

In [5]:
print(df.shape)

(40600, 50)

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40600 entries, 0 to 40599
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               40600 non-null  int64
 1   dog_name             35804 non-null  object
 2   breed                37332 non-null  object
 3   age_years            38982 non-null  float64
 4   weight_kg            32416 non-null  object
 5   height_cm            32552 non-null  object
 6   color                28851 non-null  object
 7   vaccinated           27086 non-null  object
 8   neutered             27010 non-null  object
 9   owner_city           36885 non-null  object
 10  owner_age            39516 non-null  object
 11  owner_income         40600 non-null  int64
 12  diet_type            33828 non-null  object
 13  daily_walk_minutes   40410 non-null  object
 14  barks_per_day        40333 non-null  object
 15  vet_visits_per_year  38510 non-null  object
 16  last_vet_visit       34458 non-null  object
 17  adoption_date        34406 non-null  object
 18  favorite_toy         23131 non-null  object
 19  training_level       27077 non-null  object
 20  sensor_metric_1      32616 non-null  float64
 21  sensor_metric_2      32517 non-null  float64
 22  sensor_metric_3      32563 non-null  float64
 23  sensor_metric_4      32535 non-null  float64
 24  sensor_metric_5      32494 non-null  float64
 25  sensor_metric_6      32495 non-null  float64
 26  sensor_metric_7      32450 non-null  float64
 27  sensor_metric_8      32553 non-null  float64
 28  sensor_metric_9      32407 non-null  float64
 29  sensor_metric_10     32487 non-null  float64
 30  sensor_metric_11     32457 non-null  float64
 31  sensor_metric_12     32440 non-null  float64
 32  sensor_metric_13     32384 non-null  float64
 33  sensor_metric_14     32602 non-null  float64
 34  sensor_metric_15     32425 non-null  float64
 35  sensor_metric_16     32527 non-null  float64
 36  sensor_metric_17     32486 non-null  float64
 37  sensor_metric_18     32464 non-null  float64
 38  sensor_metric_19     32445 non-null  float64
 39  sensor_metric_20     32484 non-null  float64
 40  sensor_metric_21     24301 non-null  object
 41  sensor_metric_22     24223 non-null  object
 42  sensor_metric_23     24340 non-null  object
 43  sensor_metric_24     24335 non-null  object
 44  sensor_metric_25     24156 non-null  object
 45  sensor_metric_26     24394 non-null  object
 46  sensor_metric_27     24301 non-null  object
 47  sensor_metric_28     24443 non-null  object
 48  sensor_metric_29     24346 non-null  object
 49  sensor_metric_30     24375 non-null  object
dtypes: float64(21), int64(2), object(27)
memory usage: 15.5+ MB
None

In [7]:
# Check missing values
print(df.isnull().sum())

dog_id                     0
dog_name                4796
breed                   3268
age_years               1618
weight_kg               8184
height_cm               8048
color                  11749
vaccinated             13514
neutered               13590
owner_city              3715
owner_age               1084
owner_income               0
diet_type               6772
daily_walk_minutes       190
barks_per_day            267
vet_visits_per_year     2090
last_vet_visit          6142
adoption_date           6194
favorite_toy           17469
training_level         13523
sensor_metric_1         7984
sensor_metric_2         8083
sensor_metric_3         8037
sensor_metric_4         8065
sensor_metric_5         8106
sensor_metric_6         8105
sensor_metric_7         8150
sensor_metric_8         8047
sensor_metric_9         8193
sensor_metric_10        8113
sensor_metric_11        8143
sensor_metric_12        8160
sensor_metric_13        8216
sensor_metric_14        7998
sensor_metric_15        8175
sensor_metric_16        8073
sensor_metric_17        8114
sensor_metric_18        8136
sensor_metric_19        8155
sensor_metric_20        8116
sensor_metric_21       16299
sensor_metric_22       16377
sensor_metric_23       16260
sensor_metric_24       16265
sensor_metric_25       16444
sensor_metric_26       16206
sensor_metric_27       16299
sensor_metric_28       16157
sensor_metric_29       16254
sensor_metric_30       16225
dtype: int64

### Step 1
Right now this dataset has:

"missing"

"error"

"unknown"

actual NaN

In [ ]:
# Replace "missing", "error", and "unknown" with NaN
df.replace(["missing", "error", "unknown"], pd.NA, inplace=True)

### Step 2
Columns like:

weight_kg

height_cm

owner_age

daily_walk_minutes

barks_per_day

are object but should be numeric

In [ ]:
cols_to_numeric = [
    "weight_kg", "height_cm", "owner_age",
    "daily_walk_minutes", "barks_per_day",
    "vet_visits_per_year"
]

for col in cols_to_numeric:
    df[col] = pd.to_numeric(df[col], errors='coerce') # errors = coerce will convert invalid parsing to NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40600 entries, 0 to 40599
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               40600 non-null  int64
 1   dog_name             35804 non-null  object
 2   breed                37332 non-null  object
 3   age_years            38982 non-null  float64
 4   weight_kg            24406 non-null  float64
 5   height_cm            24440 non-null  float64
 6   color                28851 non-null  object
 7   vaccinated           27086 non-null  object
 8   neutered             27010 non-null  object
 9   owner_city           36885 non-null  object
 10  owner_age            39004 non-null  float64
 11  owner_income         40600 non-null  int64
 12  diet_type            33828 non-null  object
 13  daily_walk_minutes   40237 non-null  float64
 14  barks_per_day        40183 non-null  float64
 15  vet_visits_per_year  36326 non-null  float64
 16  last_vet_visit       34458 non-null  object
 17  adoption_date        34406 non-null  object
 18  favorite_toy         23131 non-null  object
 19  training_level       20277 non-null  object
 20  sensor_metric_1      32616 non-null  float64
 21  sensor_metric_2      32517 non-null  float64
 22  sensor_metric_3      32563 non-null  float64
 23  sensor_metric_4      32535 non-null  float64
 24  sensor_metric_5      32494 non-null  float64
 25  sensor_metric_6      32495 non-null  float64
 26  sensor_metric_7      32450 non-null  float64
 27  sensor_metric_8      32553 non-null  float64
 28  sensor_metric_9      32407 non-null  float64
 29  sensor_metric_10     32487 non-null  float64
 30  sensor_metric_11     32457 non-null  float64
 31  sensor_metric_12     32440 non-null  float64
 32  sensor_metric_13     32384 non-null  float64
 33  sensor_metric_14     32602 non-null  float64
 34  sensor_metric_15     32425 non-null  float64
 35  sensor_metric_16     32527 non-null  float64
 36  sensor_metric_17     32486 non-null  float64
 37  sensor_metric_18     32464 non-null  float64
 38  sensor_metric_19     32445 non-null  float64
 39  sensor_metric_20     32484 non-null  float64
 40  sensor_metric_21     8077 non-null   object
 41  sensor_metric_22     8065 non-null   object
 42  sensor_metric_23     8126 non-null   object
 43  sensor_metric_24     8108 non-null   object
 44  sensor_metric_25     8007 non-null   object
 45  sensor_metric_26     8079 non-null   object
 46  sensor_metric_27     7968 non-null   object
 47  sensor_metric_28     8124 non-null   object
 48  sensor_metric_29     8112 non-null   object
 49  sensor_metric_30     8265 non-null   object
dtypes: float64(27), int64(2), object(21)
memory usage: 15.5+ MB

### Step 4
 #### Fix Invalid Values

Example:

age_years = -1 -- impossible

In [12]:
df.loc[df["age_years"] < 0, "age_years"] = pd.NA

In [13]:
df.describe()

,dog_id,age_years,weight_kg,height_cm,owner_age,owner_income,daily_walk_minutes,barks_per_day,vet_visits_per_year,sensor_metric_1,...,sensor_metric_11,sensor_metric_12,sensor_metric_13,sensor_metric_14,sensor_metric_15,sensor_metric_16,sensor_metric_17,sensor_metric_18,sensor_metric_19,sensor_metric_20
count,40600.000000,34261.000000,24406.000000,24440.000000,39004.000000,40600.000000,40237.000000,40183.000000,36326.000000,32616.000000,...,32457.000000,32440.000000,32384.000000,32602.000000,32425.000000,32527.000000,32486.000000,32464.000000,32445.000000,32484.000000
mean,4493.743744,10.566913,27.620340,27.653613,51.912881,85273.086626,89.546760,149.720703,6.010571,50.100557,...,49.788374,50.147277,49.978213,49.933915,49.855479,50.012600,49.971514,49.976304,50.208527,50.069270
std,2018.802066,6.337842,13.008783,12.975099,21.737492,37607.779476,63.658358,86.830373,4.926158,19.918998,...,19.886773,20.091048,19.977766,20.025882,20.009208,19.997773,19.947837,19.999906,19.960152,20.051670
min,1000.000000,0.000000,5.000000,5.000000,15.000000,20000.000000,-20.000000,0.000000,-2.000000,-28.760949,...,-30.922819,-35.110943,-39.516300,-34.891226,-50.418526,-31.168171,-24.900630,-27.805367,-28.031676,-27.383791
25%,2739.000000,5.000000,16.310000,16.450000,33.000000,52656.000000,34.000000,74.000000,2.000000,36.601348,...,36.372089,36.669018,36.716009,36.427784,36.420521,36.635412,36.384714,36.544201,36.789953,36.665086
50%,4481.000000,11.000000,27.720000,27.720000,52.000000,85282.500000,89.000000,150.000000,6.000000,50.197779,...,49.892856,50.074044,49.911401,49.933203,49.736057,50.143305,49.956955,49.995916,50.190930,50.150160
75%,6247.000000,16.000000,38.907500,38.940000,71.000000,117822.250000,145.000000,225.000000,10.000000,63.608140,...,63.258527,63.684409,63.162572,63.493839,63.359564,63.414661,63.614550,63.269117,63.722669,63.436503
max,7999.000000,21.000000,50.000000,50.000000,89.000000,149999.000000,199.000000,299.000000,14.000000,127.996159,...,147.054478,139.733367,129.621540,126.303564,143.651661,137.662104,131.518860,135.703309,127.090900,128.012552

### Step 5
#### Covert date column

Columns:

last_vet_visit

adoption_date

In [14]:
df["last_vet_visit"] = pd.to_datetime(df["last_vet_visit"], errors='coerce')
df["adoption_date"] = pd.to_datetime(df["adoption_date"], errors='coerce') # errors = coerce will convert invalid dates to NaT (Not a Time)

### Step 6
#### Clean categorical data
Example: vaccinated, neutered

In [15]:
df["vaccinated"].value_counts()

vaccinated
Yes    13606
No     13480
Name: count, dtype: int64

In [16]:
df["vaccinated"] = df["vaccinated"].str.lower().str.strip()
df["neutered"] = df["neutered"].str.lower().str.strip()

In [17]:
df["vaccinated"] = df["vaccinated"].map({"yes": 1, "no": 0})
df["neutered"] = df["neutered"].map({"yes": 1, "no": 0})

In [19]:
df.isnull().sum()

dog_id                     0
dog_name                4796
breed                   3268
age_years               6339
weight_kg              16194
height_cm              16160
color                  11749
vaccinated             13514
neutered               13590
owner_city              3715
owner_age               1596
owner_income               0
diet_type               6772
daily_walk_minutes       363
barks_per_day            417
vet_visits_per_year     4274
last_vet_visit         30517
adoption_date          30445
favorite_toy           17469
training_level         20323
sensor_metric_1         7984
sensor_metric_2         8083
sensor_metric_3         8037
sensor_metric_4         8065
sensor_metric_5         8106
sensor_metric_6         8105
sensor_metric_7         8150
sensor_metric_8         8047
sensor_metric_9         8193
sensor_metric_10        8113
sensor_metric_11        8143
sensor_metric_12        8160
sensor_metric_13        8216
sensor_metric_14        7998
sensor_metric_15        8175
sensor_metric_16        8073
sensor_metric_17        8114
sensor_metric_18        8136
sensor_metric_19        8155
sensor_metric_20        8116
sensor_metric_21       32523
sensor_metric_22       32535
sensor_metric_23       32474
sensor_metric_24       32492
sensor_metric_25       32593
sensor_metric_26       32521
sensor_metric_27       32632
sensor_metric_28       32476
sensor_metric_29       32488
sensor_metric_30       32335
dtype: int64

### Step 7
####  Handle missing values
Option A: Drop rows (if too many missing)

Option B: Fill numeric values

Option C: Fill categorical

In [ ]:
# option A: drop rows with missing dog names
df.dropna(subset=["dog_name"], inplace=True)

In [21]:
df.isnull().sum()

dog_id                     0
dog_name                   0
breed                   2880
age_years               5548
weight_kg              14271
height_cm              14273
color                  10331
vaccinated             11914
neutered               12007
owner_city              3312
owner_age               1412
owner_income               0
diet_type               5991
daily_walk_minutes       322
barks_per_day            367
vet_visits_per_year     3752
last_vet_visit         26878
adoption_date          26827
favorite_toy           15355
training_level         17958
sensor_metric_1         6992
sensor_metric_2         7135
sensor_metric_3         7104
sensor_metric_4         7135
sensor_metric_5         7163
sensor_metric_6         7144
sensor_metric_7         7206
sensor_metric_8         7068
sensor_metric_9         7223
sensor_metric_10        7168
sensor_metric_11        7230
sensor_metric_12        7218
sensor_metric_13        7291
sensor_metric_14        7029
sensor_metric_15        7185
sensor_metric_16        7128
sensor_metric_17        7153
sensor_metric_18        7157
sensor_metric_19        7182
sensor_metric_20        7152
sensor_metric_21       28683
sensor_metric_22       28712
sensor_metric_23       28638
sensor_metric_24       28656
sensor_metric_25       28749
sensor_metric_26       28663
sensor_metric_27       28803
sensor_metric_28       28722
sensor_metric_29       28673
sensor_metric_30       28561
dtype: int64

In [ ]:
# option B: 
df["age_years"] =df["age_years"].fillna(df["age_years"].median(), inplace=True)
df["weight_kg"] = df["weight_kg"].fillna(df["weight_kg"].mean(), inplace=True)

In [ ]:
# option C:
df["breed"].fillna("Unknown", inplace=True)

### Step 8:
#### Fix Sensor Columns
 

sensor_metric_1 → float 

sensor_metric_21+ → object  (dirty)

Convert them:

In [28]:
sensor_cols = [col for col in df.columns if "sensor_metric_" in col]

for col in sensor_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

### Step 9
#### Remove duplicates

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 35274 entries, 0 to 40599
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               35274 non-null  int64
 1   dog_name             35274 non-null  object
 2   breed                35274 non-null  object
 3   age_years            0 non-null      object
 4   weight_kg            0 non-null      object
 5   height_cm            21217 non-null  float64
 6   color                25096 non-null  object
 7   vaccinated           23542 non-null  float64
 8   neutered             23449 non-null  float64
 9   owner_city           32005 non-null  object
 10  owner_age            33888 non-null  float64
 11  owner_income         35274 non-null  int64
 12  diet_type            29368 non-null  object
 13  daily_walk_minutes   34959 non-null  float64
 14  barks_per_day        34912 non-null  float64
 15  vet_visits_per_year  31573 non-null  float64
 16  last_vet_visit       8789 non-null   datetime64[ns]
 17  adoption_date        8835 non-null   datetime64[ns]
 18  favorite_toy         20147 non-null  object
 19  training_level       17589 non-null  object
 20  sensor_metric_1      28387 non-null  float64
 21  sensor_metric_2      28240 non-null  float64
 22  sensor_metric_3      28285 non-null  float64
 23  sensor_metric_4      28253 non-null  float64
 24  sensor_metric_5      28217 non-null  float64
 25  sensor_metric_6      28247 non-null  float64
 26  sensor_metric_7      28182 non-null  float64
 27  sensor_metric_8      28322 non-null  float64
 28  sensor_metric_9      28151 non-null  float64
 29  sensor_metric_10     28207 non-null  float64
 30  sensor_metric_11     28153 non-null  float64
 31  sensor_metric_12     28177 non-null  float64
 32  sensor_metric_13     28076 non-null  float64
 33  sensor_metric_14     28346 non-null  float64
 34  sensor_metric_15     28194 non-null  float64
 35  sensor_metric_16     28252 non-null  float64
 36  sensor_metric_17     28245 non-null  float64
 37  sensor_metric_18     28210 non-null  float64
 38  sensor_metric_19     28191 non-null  float64
 39  sensor_metric_20     28231 non-null  float64
 40  sensor_metric_21     7026 non-null   float64
 41  sensor_metric_22     6980 non-null   float64
 42  sensor_metric_23     7082 non-null   float64
 43  sensor_metric_24     7029 non-null   float64
 44  sensor_metric_25     6951 non-null   float64
 45  sensor_metric_26     7045 non-null   float64
 46  sensor_metric_27     6894 non-null   float64
 47  sensor_metric_28     6970 non-null   float64
 48  sensor_metric_29     7017 non-null   float64
 49  sensor_metric_30     7122 non-null   float64
dtypes: datetime64[ns](2), float64(37), int64(2), object(9)
memory usage: 13.7+ MB
None

In [31]:
print(df.isnull().sum())

dog_id                     0
dog_name                   0
breed                      0
age_years              35274
weight_kg              35274
height_cm              14057
color                  10178
vaccinated             11732
neutered               11825
owner_city              3269
owner_age               1386
owner_income               0
diet_type               5906
daily_walk_minutes       315
barks_per_day            362
vet_visits_per_year     3701
last_vet_visit         26485
adoption_date          26439
favorite_toy           15127
training_level         17685
sensor_metric_1         6887
sensor_metric_2         7034
sensor_metric_3         6989
sensor_metric_4         7021
sensor_metric_5         7057
sensor_metric_6         7027
sensor_metric_7         7092
sensor_metric_8         6952
sensor_metric_9         7123
sensor_metric_10        7067
sensor_metric_11        7121
sensor_metric_12        7097
sensor_metric_13        7198
sensor_metric_14        6928
sensor_metric_15        7080
sensor_metric_16        7022
sensor_metric_17        7029
sensor_metric_18        7064
sensor_metric_19        7083
sensor_metric_20        7043
sensor_metric_21       28248
sensor_metric_22       28294
sensor_metric_23       28192
sensor_metric_24       28245
sensor_metric_25       28323
sensor_metric_26       28229
sensor_metric_27       28380
sensor_metric_28       28304
sensor_metric_29       28257
sensor_metric_30       28152
dtype: int64

### Decide drop or keep

Rule:
* If >50% missing → consider dropping column
* If important → fill smartly

In [32]:
df.drop(columns=["age_years", "weight_kg"], inplace=True)

In [ ]:
# df["height_cm"].fillna(df["height_cm"].median(), inplace=True)
df["height_cm"] = df["height_cm"].fillna(df["height_cm"].median())

In [38]:
df["color"]= df["color"].fillna(df["color"].mode()[0])

In [39]:
df["vaccinated"] = df["vaccinated"].fillna(df["vaccinated"].mode()[0])

In [40]:
df["neutered"] = df["neutered"].fillna(df["neutered"].mode()[0])

In [41]:
df.isnull().sum()

dog_id                     0
dog_name                   0
breed                      0
height_cm                  0
color                      0
vaccinated                 0
neutered                   0
owner_city              3269
owner_age               1386
owner_income               0
diet_type               5906
daily_walk_minutes       315
barks_per_day            362
vet_visits_per_year     3701
last_vet_visit         26485
adoption_date          26439
favorite_toy           15127
training_level         17685
sensor_metric_1         6887
sensor_metric_2         7034
sensor_metric_3         6989
sensor_metric_4         7021
sensor_metric_5         7057
sensor_metric_6         7027
sensor_metric_7         7092
sensor_metric_8         6952
sensor_metric_9         7123
sensor_metric_10        7067
sensor_metric_11        7121
sensor_metric_12        7097
sensor_metric_13        7198
sensor_metric_14        6928
sensor_metric_15        7080
sensor_metric_16        7022
sensor_metric_17        7029
sensor_metric_18        7064
sensor_metric_19        7083
sensor_metric_20        7043
sensor_metric_21       28248
sensor_metric_22       28294
sensor_metric_23       28192
sensor_metric_24       28245
sensor_metric_25       28323
sensor_metric_26       28229
sensor_metric_27       28380
sensor_metric_28       28304
sensor_metric_29       28257
sensor_metric_30       28152
dtype: int64

In [ ]:
df.drop(columns=["last_vet_visit", "adoption_date"], inplace=True)
# or
# df["last_vet_visit"].fillna(method="ffill", inplace=True)

### Remove unrealistic values

In [48]:
df.loc[df["owner_age"] < 10, "owner_age"] = pd.NA
df.loc[df["owner_age"] > 100, "owner_age"] = pd.NA

#### Outlier detection

In [49]:
df.describe()

,dog_id,height_cm,vaccinated,neutered,owner_age,owner_income,daily_walk_minutes,barks_per_day,vet_visits_per_year,sensor_metric_1,...,sensor_metric_21,sensor_metric_22,sensor_metric_23,sensor_metric_24,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30
count,35274.000000,35274.000000,35274.000000,35274.000000,33888.000000,35274.000000,34959.000000,34912.000000,31573.000000,28387.000000,...,7026.00,6.980000e+03,7.082000e+03,7.029000e+03,6951.00,7045.00,6.894000e+03,6970.00,7.017000e+03,7122.00
mean,4496.343397,27.651099,0.668765,0.328259,51.912476,85317.228695,89.716754,149.639895,6.000475,50.131392,...,7.06,4.983000e+01,8.212000e+01,3.340000e+01,46.26,60.19,4.042000e+01,66.28,1.535000e+01,70.55
std,2016.837792,10.057858,0.470664,0.469586,21.713268,37576.476407,63.706334,86.721995,4.919416,19.939157,...,0.00,7.105936e-15,1.421186e-14,7.105933e-15,0.00,0.00,7.105943e-15,0.00,1.776483e-15,0.00
min,1000.000000,5.000000,0.000000,0.000000,15.000000,20000.000000,-20.000000,0.000000,-2.000000,-28.760949,...,7.06,4.983000e+01,8.212000e+01,3.340000e+01,46.26,60.19,4.042000e+01,66.28,1.535000e+01,70.55
25%,2742.250000,23.990000,0.000000,0.000000,33.000000,52730.000000,34.000000,74.000000,2.000000,36.630613,...,7.06,4.983000e+01,8.212000e+01,3.340000e+01,46.26,60.19,4.042000e+01,66.28,1.535000e+01,70.55
50%,4490.000000,27.730000,1.000000,0.000000,52.000000,85347.000000,90.000000,150.000000,6.000000,50.282471,...,7.06,4.983000e+01,8.212000e+01,3.340000e+01,46.26,60.19,4.042000e+01,66.28,1.535000e+01,70.55
75%,6247.000000,31.417500,1.000000,1.000000,71.000000,117728.000000,145.000000,225.000000,10.000000,63.664938,...,7.06,4.983000e+01,8.212000e+01,3.340000e+01,46.26,60.19,4.042000e+01,66.28,1.535000e+01,70.55
max,7999.000000,50.000000,1.000000,1.000000,89.000000,149999.000000,199.000000,299.000000,14.000000,127.996159,...,7.06,4.983000e+01,8.212000e+01,3.340000e+01,46.26,60.19,4.042000e+01,66.28,1.535000e+01,70.55

In [50]:
df["breed"] = df["breed"].str.lower().str.strip()
df["color"] = df["color"].str.lower().str.strip()

In [51]:
df.isnull().sum()

dog_id                     0
dog_name                   0
breed                      0
height_cm                  0
color                      0
vaccinated                 0
neutered                   0
owner_city              3269
owner_age               1386
owner_income               0
diet_type               5906
daily_walk_minutes       315
barks_per_day            362
vet_visits_per_year     3701
favorite_toy           15127
training_level         17685
sensor_metric_1         6887
sensor_metric_2         7034
sensor_metric_3         6989
sensor_metric_4         7021
sensor_metric_5         7057
sensor_metric_6         7027
sensor_metric_7         7092
sensor_metric_8         6952
sensor_metric_9         7123
sensor_metric_10        7067
sensor_metric_11        7121
sensor_metric_12        7097
sensor_metric_13        7198
sensor_metric_14        6928
sensor_metric_15        7080
sensor_metric_16        7022
sensor_metric_17        7029
sensor_metric_18        7064
sensor_metric_19        7083
sensor_metric_20        7043
sensor_metric_21       28248
sensor_metric_22       28294
sensor_metric_23       28192
sensor_metric_24       28245
sensor_metric_25       28323
sensor_metric_26       28229
sensor_metric_27       28380
sensor_metric_28       28304
sensor_metric_29       28257
sensor_metric_30       28152
dtype: int64

In [53]:
df.dropna(inplace=True)

In [54]:
df.isnull().sum()

dog_id                 0
dog_name               0
breed                  0
height_cm              0
color                  0
vaccinated             0
neutered               0
owner_city             0
owner_age              0
owner_income           0
diet_type              0
daily_walk_minutes     0
barks_per_day          0
vet_visits_per_year    0
favorite_toy           0
training_level         0
sensor_metric_1        0
sensor_metric_2        0
sensor_metric_3        0
sensor_metric_4        0
sensor_metric_5        0
sensor_metric_6        0
sensor_metric_7        0
sensor_metric_8        0
sensor_metric_9        0
sensor_metric_10       0
sensor_metric_11       0
sensor_metric_12       0
sensor_metric_13       0
sensor_metric_14       0
sensor_metric_15       0
sensor_metric_16       0
sensor_metric_17       0
sensor_metric_18       0
sensor_metric_19       0
sensor_metric_20       0
sensor_metric_21       0
sensor_metric_22       0
sensor_metric_23       0
sensor_metric_24       0
sensor_metric_25       0
sensor_metric_26       0
sensor_metric_27       0
sensor_metric_28       0
sensor_metric_29       0
sensor_metric_30       0
dtype: int64

In [55]:
df.to_csv("dogs_cleaned_final.csv", index=False)